#!/bin/bash
if [ ! -r "$HOME/Desktop/Tools" ];
then
	mkdir "$HOME/Desktop/Tools"
	chown "$USER" "$HOME/Desktop/Tools"
fi
unzip "./CameraControl.zip"
cp -Rf "./CameraControl.app" "$HOME/Desktop/Tools/"
chown -R "$USER" "$HOME/Desktop/Tools/CameraControl.app"