#!/bin/bash
set -x
./BackupESP "$1" "$2" "$3"
./Generate
cp /tmp/config.plist /Volumes/EFI/EFI/CLOVER/
rm /tmp/config.plist

cd /tmp/tempDSDT
ACPI_Tables="$(ioreg -lw0 | grep 'ACPI Tables' | cut -f2 -d '{' | tr -d '}' | tr ',' '\012')"

#mv ./Mini-SSDT-DualLink.aml ./Mini-SSDT-DualLink.aml.bak
#mv ./Mini-SSDT-IMEI.aml ./Mini-SSDT-IMEI.aml.bak

# Extract Tables from Dump
for table in ${ACPI_Tables}; do
    tableName=$(echo $table | cut -f1 -d '=' | tr -d '"')
    printf "${tableName} \n"
    if [[ $tableName == *DSDT* ]] || [[ $tableName == *SSDT* ]]
    then
	    tableData=$(echo "$table" | cut -f2 -d '<' | tr -d '>')
	    echo "$tableData" | xxd -r -p > "./${tableName}.aml"
	fi
done

cp ./*.aml /Volumes/EFI/EFI/CLOVER/acpi/origin/

./iaslpbi -da *.aml

VanillaCheck=`cat ./DSDT.dsl | grep 'If (CondRefOf (FPED))\|External (_SB_.ISCT)'`

if [ "$VanillaCheck" == "" -a -f ./4x*.txt ] || [ "$VanillaCheck" != "" -a ! -f ./4x*.txt ]
then
	cp ./warning.txt "$HOME/Desktop/DSDT Warning.txt"
	#cp ./Mini-SSDT-DualLink.aml.bak "$HOME/Desktop/Mini-SSDT-DualLink.aml"
	#cp ./Mini-SSDT-IMEI.aml.bak "$HOME/Desktop/Mini-SSDT-IMEI.aml"
else
	
	for patch in "4x30s.txt" \
		"4x40s_IvyBridge.txt" \
		"4x40s_SandyBridge.txt" \
		"4x0G1.txt" \
		"03a_HDMI.txt" \
		"03b_1080p+HDMI.txt" \
		"03c_Haswell.txt" \
		"04a_FanPatch.txt" \
		"04b_FanQuiet.txt" \
		"04c_FanSpeed.txt" \
		"08a_AR9285.txt" \
		"08b_BCM4322x.txt" \
		"09_USB3_4x40s_Mieze.txt" \
		"10_LPC_4x40s_Sandy_SL.txt" \
		"12_Brightness.txt" \
		"12_Brightness_Haswell.txt" \
		"12c_generic_BCL.txt"
	do
		if [ -f $patch ]
		then
			if [ $patch == "4x0G1.txt" ]
			then
				rm ./03a_HDMI.txt
				rm ./03b_1080p+HDMI.txt
				rm ./04a_FanPatch.txt
				rm ./04b_FanQuiet.txt
			fi
			./patchmatic ./DSDT.dsl ./$patch ./DSDT.dsl
		fi
	done

	GraphicCheck=''
	for file in ./SSDT*.dsl
	do
		GraphicCheck=`cat $file | grep -i '\_SB.PCI0.PEGP.DGFX'`
		if [[ $GraphicCheck != '' ]]
		then
			./patchmatic ./DSDT.dsl ./11b_Radeon_OFF_DSDT.txt ./DSDT.dsl			
			./patchmatic $file ./11a_Radeon_OFF_SSDT.txt $file
			./iaslpbi -p SSDT-1 $file
			cp ./SSDT-1.aml /Volumes/EFI/EFI/CLOVER/acpi/patched/SSDT-1.aml
			break
		fi
	done

	./iaslpbi -p DSDT ./DSDT.dsl
	cp ./DSDT.aml /Volumes/EFI/EFI/CLOVER/acpi/patched/DSDT.aml
fi
rm -rf /tmp/tempDSDT

