#!/bin/bash
set -x
./BackupESP "$1" "$2" "$3"

CloverConfigGenerate=`/usr/libexec/PlistBuddy -c "Print :CloverConfigGenerate" /tmp/PBI.plist`
CloverModel=`/usr/libexec/PlistBuddy -c "Print :CloverModel" /tmp/PBI.plist`

if [ "$CloverConfigGenerate" != "no" ]
then
	./Generate
	cp /tmp/config.plist /Volumes/EFI/EFI/CLOVER/
	rm /tmp/config.plist
fi


cd /tmp/tempDSDT


if [ -f /Volumes/CLOVER/EFI/CLOVER/ACPI/origin/DSDT.aml ]
then
	# get original DSDT from CLOVER USB
	cp /Volumes/CLOVER/EFI/CLOVER/ACPI/origin/DSDT.aml .
	cp /Volumes/CLOVER/EFI/CLOVER/ACPI/origin/SSDT*.aml .
	./iasl -da *.aml
	if [[ ! -f ./DSDT.dsl ]]
	then
		for file in ./SSDT*.aml; do
	        rm "$file" # If it does what you want, remove the echo
	        ./iasl -da *.aml
	        if [[ -f ./DSDT.dsl ]]
	        then
	        	break
	        fi
    	done
	fi	
elif [ -f /Volumes/EFI/EFI/CLOVER/ACPI/origin/DSDT.aml ]
then
	# get original DSDT from EFI partition
	cp /Volumes/EFI/EFI/CLOVER/ACPI/origin/DSDT.aml .
	cp /Volumes/EFI/EFI/CLOVER/ACPI/origin/SSDT*.aml .
	./iasl -da *.aml

	if [[ ! -f ./DSDT.dsl ]]
	then
		for file in ./SSDT*.aml; do
	        rm "$file" # If it does what you want, remove the echo
	        ./iasl -da *.aml
	        if [[ -f ./DSDT.dsl ]]
	        then
	        	break
	        fi
    	done
	fi	
else 
	#statements
	ACPI_Tables="$(ioreg -lw0 | grep 'ACPI Tables' | cut -f2 -d '{' | tr -d '}' | tr ',' '\012')"

	# Extract Tables from Dump
	for table in ${ACPI_Tables}; do
	    tableName=$(echo $table | cut -f1 -d '=' | tr -d '"')
	    printf "${tableName} \n"
	    if [[ $tableName == *DSDT* ]] || [[ $tableName == *SSDT* ]]
	    then
		    tableData=$(echo "$table" | cut -f2 -d '<' | tr -d '>')
		    echo "$tableData" | xxd -r -p > "./${tableName}.aml"
		fi
	done
	./iasl -da *.aml
	if [[ ! -f ./DSDT.dsl ]]
	then
		for file in ./SSDT*.aml; do
	        rm "$file" # If it does what you want, remove the echo
	        ./iasl -da *.aml
	        if [[ -f ./DSDT.dsl ]]
	        then
	        	break
	        fi
    	done
	fi	
fi

cp ./*.aml /Volumes/EFI/EFI/CLOVER/acpi/origin/



VanillaCheck=`cat ./DSDT.dsl | grep 'If (CondRefOf (FPED))\|External (_SB_.ISCT, UnknownObj)'`

if [ "$VanillaCheck" == "" -a -f ./4x*.txt ] || [ "$VanillaCheck" != "" -a ! -f ./4x*.txt ]
then
	/usr/bin/osascript <<EOT
tell application "Finder"
	activate
	set myReply to button returned of (display dialog "If you see this warning message, that means:

1. You haven't pressed F4 at Clover screen.
2. You haven't selected the right main model-specific patch.

If you want to make yourself a new patched DSDT, you should do the following:

Press F4 at Clover screen
Run PBI Clover Edition again and select correct DSDT options." )
end tell
EOT
else
	if [ -f "4x0G1.txt" ]
	then
		rm ./03a_HDMI.txt
		rm ./03b_1080p+HDMI.txt
		rm ./04a_FanPatch.txt
		rm ./04b_FanQuiet.txt
	fi

	if [ -f  "4x40s_AMD.txt" ]
	then
		rm ./03a_HDMI.txt
		rm ./03b_1080p+HDMI.txt
	fi

	if [ "$CloverModel" == "4x40" ]
	then
		rm ./4x40s_SandyBridge.txt
	fi

	if [ "$CloverModel" == "4x40sb" ]
	then
		rm ./4x40s_IvyBridge.txt
	fi


	
	for patch in "4x30s.txt" \
		"4x40s_IvyBridge.txt" \
		"4x40s_SandyBridge.txt" \
		"4x40s_AMD.txt" \
		"4x0G1.txt" \
		"03a_HDMI.txt" \
		"03b_1080p+HDMI.txt" \
		"03c_Haswell.txt" \
		"04a_FanPatch.txt" \
		"04b_FanQuiet.txt" \
		"04c_FanSpeed.txt" \
		"08a_AR9285.txt" \
		"08b_BCM4322x.txt" \
		"09_USB3_4x40s_Mieze.txt" \
		"10_LPC_4x40s_Sandy_SL.txt" \
		"12_Brightness.txt" \
		"12_Brightness_Haswell.txt" \
		"12c_generic_BCL.txt" \
		"13a_ProBookKeyboard.txt" \
		"13b_EliteBookKeyboard.txt"
	do
		./patchmatic ./DSDT.dsl ./$patch ./DSDT.dsl
	done

	if [ -f "4x0G1.txt" ]
	then
		for file in ./SSDT*.dsl
		do
			B0D3Check=`cat $file | grep -i 'Device (B0D3)'`
			if [[ $B0D3Check != '' ]]
			then		
				./patchmatic $file ./03c_Haswell.txt $file
				./iasl -p SSDT-1 $file
				cp ./SSDT-1.aml /Volumes/EFI/EFI/CLOVER/acpi/patched/SSDT-1.aml
				break
			fi
		done
	fi

	GraphicCheck=''
	for file in ./SSDT*.dsl
	do
		GraphicCheck=`cat $file | grep -i '\_SB.PCI0.PEGP.DGFX'`
		if [[ $GraphicCheck != '' ]]
		then
			./patchmatic ./DSDT.dsl ./11b_Radeon_OFF_DSDT.txt ./DSDT.dsl			
			./patchmatic $file ./11a_Radeon_OFF_SSDT.txt $file

			if [ -f "4x0G1.txt" ]
			then
				./iasl -p SSDT-2 $file
				cp ./SSDT-2.aml /Volumes/EFI/EFI/CLOVER/acpi/patched/SSDT-2.aml
			else
				./iasl -p SSDT-1 $file
				cp ./SSDT-1.aml /Volumes/EFI/EFI/CLOVER/acpi/patched/SSDT-1.aml
			fi

			break
		fi
	done
	

	./iasl -p DSDT ./DSDT.dsl
	cp ./DSDT.aml /Volumes/EFI/EFI/CLOVER/acpi/patched/DSDT.aml
fi
