#!/bin/bash
set -x

CloverConfigGenerate=`/usr/libexec/PlistBuddy -c "Print :CloverConfigGenerate" /tmp/PBI.plist`
CloverModel=`/usr/libexec/PlistBuddy -c "Print :CloverModel" /tmp/PBI.plist`
osxver=`/usr/libexec/PlistBuddy -c 'Print ProductVersion' "${3}"/System/Library/CoreServices/SystemVersion.plist`

exitcode=0

if [ "$CloverConfigGenerate" != "no" ] || [ ! -f /Volumes/CLOVER/EFI/CLOVER/config.plist ]
then
	./Generate
	cp /tmp/config.plist /Volumes/EFI/EFI/CLOVER/
	rm /tmp/config.plist
fi

cd /tmp/tempDSDT


if [ -f /Volumes/CLOVER/EFI/CLOVER/ACPI/origin/DSDT.aml ]
then
	# get original DSDT from CLOVER USB
	cp /Volumes/CLOVER/EFI/CLOVER/ACPI/origin/DSDT.aml .
	cp /Volumes/CLOVER/EFI/CLOVER/ACPI/origin/SSDT*.aml .

elif [ -f /Volumes/EFI/EFI/CLOVER/ACPI/origin/DSDT.aml ]
then
	# get original DSDT from EFI partition
	cp /Volumes/EFI/EFI/CLOVER/ACPI/origin/DSDT.aml .
	cp /Volumes/EFI/EFI/CLOVER/ACPI/origin/SSDT*.aml .
else
	./patchmatic -extract
fi

./iasl -da DSDT.aml SSDT*.aml

if [[ ! -f ./DSDT.dsl ]]
then
	list="DSDT.aml"
	for file in ./SSDT*.aml; do
		rm -rf ./*.dsl
		./iasl -da $list $file

        if [[ -f ./DSDT.dsl ]]
        then
        	list="$list $file"
        fi
	done

	./iasl -da $list
fi

if [ ! -f ./DSDT.dsl ]
then
/usr/bin/osascript <<EOT
tell application "Finder"
    activate
    display dialog "If you see this warning message, that means:

You haven't pressed F4 at Clover screen.

If you want to make yourself a new patched DSDT, you should do the following:

Press F4 at Clover screen
Run PBI Clover Edition again and select correct DSDT options." buttons {"OK"} default button "OK" with icon note with title "Non-vanilla DSDT!"
end tell
EOT
exitcode=1
else
	cp ./DSDT.dsl /Volumes/EFI/EFI/CLOVER/acpi/patched/DSDT_origin.dsl

	VanillaCheck=`cat ./DSDT.dsl | grep 'Device (WMID)\|If (CondRefOf (FPED))'`

	if [ "$VanillaCheck" == "" ]
	then
		/usr/bin/osascript <<EOT
tell application "Finder"
    activate
    display dialog "If you see this warning message, that means:

	1. You haven't pressed F4 at Clover screen.
	2. You haven't selected the right main model-specific patch.

If you want to make yourself a new patched DSDT, you should do the following:

Press F4 at Clover screen
Run PBI Clover Edition again and select correct DSDT options." buttons {"OK"} default button "OK" with icon note with title "Non-vanilla DSDT!"
end tell
EOT
exitcode=1
	else
		cp ./*.aml /Volumes/EFI/EFI/CLOVER/acpi/origin/

		if [ -f "4x0G1.txt" ] || [ -f "3x0G1.txt" ]
		then
			rm ./03a_HDMI.txt
			rm ./03b_1080p+HDMI.txt
		fi

		if [ "$CloverModel" == "6x60wAMD" ] || [ "$CloverModel" == "6x70AMD" ] || [ "$CloverModel" == "6x70NVIDIA" ]
		then
			rm ./03a_HDMI.txt
			rm ./03b_1080p+HDMI.txt
		fi

		if [ "$CloverModel" == "4x40" ]
		then
			rm ./4x40s_SandyBridge.txt
		fi

		if [ "$CloverModel" == "4x40sb" ]
		then
			rm ./4x40s_IvyBridge.txt
		fi

		if [ "$CloverModel" == "3x0G1" ]
		then
			rm ./04*.txt
		fi

		# if [[ "$osxver" == 10.9* ]]
		# then
		# 	rm ./09_USB3_4x40s_10_11.txt
		# else
		# 	rm ./09_USB3_4x40s_Mieze.txt
		# fi
		rm ./09_USB3_4x40s_Mieze.txt

		for patch in "4x30s.txt" \
			"4x40s_IvyBridge.txt" \
			"4x40s_SandyBridge.txt" \
			"6x60_AMD.txt" \
			"6x70_AMD.txt" \
			"4x0G1.txt" \
			"3x0G1.txt" \
			"03a_HDMI.txt" \
			"03b_1080p+HDMI.txt" \
			"03c_Haswell.txt" \
			"04a_FanPatch.txt" \
			"04b_FanQuiet.txt" \
			"04c_FanSpeed.txt" \
			"08a_AR9285.txt" \
			"08b_BCM4322x.txt" \
			"09_USB3_4x40s_10_11.txt" \
			"09_USB3_4x40s_Mieze.txt" \
			"10_LPC_4x40s_Sandy_SL.txt" \
			"12_Brightness.txt" \
			"12_Brightness_Haswell.txt" \
			"12c_generic_BCL.txt" \
			"13a_ProBookKeyboard.txt" \
			"13b_EliteBookKeyboard.txt" \
			"14_audio_HDEF-layout1.txt"
		do
			./patchmatic ./DSDT.dsl ./$patch ./DSDT.dsl
		done

		if [ -f "4x0G1.txt" ] || [ -f "3x0G1.txt" ]
		then
			for file in ./SSDT*.dsl
			do
				B0D3Check=`cat $file | grep -i 'Device (B0D3)'`
				if [[ $B0D3Check != '' ]]
				then
					./patchmatic $file ./03c_Haswell.txt $file
					if [ -f "3x0G1.txt" ]
					then
						./patchmatic $file ./12_Brightness_Haswell.txt $file
					fi
					./iasl -p SSDT-1 $file
					cp ./SSDT-1.aml /Volumes/EFI/EFI/CLOVER/acpi/patched/SSDT-1.aml
					break
				fi
			done
		fi

		GraphicCheck=''
		for file in ./SSDT*.dsl
		do
			GraphicCheck=`cat $file | grep -i '\_SB.PCI0.PEGP.DGFX'`
			if [[ $GraphicCheck != '' ]]
			then
				if [ "$CloverModel" == "6x60wAMD" ] || [ "$CloverModel" == "6x70AMD" ] || [ "$CloverModel" == "6x70NVIDIA" ]
				then
					cp $file /Volumes/EFI/EFI/CLOVER/acpi/patched/SSDT-1.aml
				else
					./patchmatic ./DSDT.dsl ./11b_Radeon_OFF_DSDT.txt ./DSDT.dsl			
					./patchmatic $file ./11a_Radeon_OFF_SSDT.txt $file

					if [ -f "4x0G1.txt" ] || [ -f "3x0G1.txt" ]
					then
						./iasl -p SSDT-2 $file
						cp ./SSDT-2.aml /Volumes/EFI/EFI/CLOVER/acpi/patched/SSDT-2.aml
					else
						./iasl -p SSDT-1 $file
						cp ./SSDT-1.aml /Volumes/EFI/EFI/CLOVER/acpi/patched/SSDT-1.aml
					fi
				fi

				break
			fi
		done

		if [[ $GraphicCheck == '' ]]
		then
			for file in ./SSDT*.dsl
			do
				GraphicCheck=`cat $file | grep -i '\_SB.PCI0.RP05.DGFX'`
				if [[ $GraphicCheck != '' ]]
				then
					if [ "$CloverModel" == "6x60wAMD" ] || [ "$CloverModel" == "6x70AMD" ] || [ "$CloverModel" == "6x70NVIDIA" ]
					then
						cp $file /Volumes/EFI/EFI/CLOVER/acpi/patched/SSDT-1.aml
					else
						./patchmatic ./DSDT.dsl ./11b2_Radeon_OFF_DSDT.txt ./DSDT.dsl			
						./patchmatic $file ./11a_Radeon_OFF_SSDT.txt $file

						if [ -f "4x0G1.txt" ] || [ -f "3x0G1.txt" ]
						then
							./iasl -p SSDT-2 $file
							cp ./SSDT-2.aml /Volumes/EFI/EFI/CLOVER/acpi/patched/SSDT-2.aml
						else
							./iasl -p SSDT-1 $file
							cp ./SSDT-1.aml /Volumes/EFI/EFI/CLOVER/acpi/patched/SSDT-1.aml
						fi
					fi

					break
				fi
			done

		fi

		
		rm ./DSDT.aml
		cp ./DSDT.dsl /Volumes/EFI/EFI/CLOVER/acpi/patched/DSDT.dsl
		
		./iasl -p DSDT ./DSDT.dsl
		
		if [ ! -f  "DSDT.aml" ]
		then
			./iasl4 -p DSDT ./DSDT.dsl
		fi

		if [ ! -f  "DSDT.aml" ]
		then
		/usr/bin/osascript <<EOT
tell application "Finder"
    activate
    display dialog "If you see this warning message, that means:

	1. You haven't pressed F4 at Clover screen.
	2. You haven't selected the right main model-specific patch.

If you want to make yourself a new patched DSDT, you should do the following:

Press F4 at Clover screen
Run PBI Clover Edition again and select correct DSDT options." buttons {"OK"} default button "OK" with icon note with title "Non-vanilla DSDT!"
end tell
EOT
exitcode=1
		else
			cp ./DSDT.aml /Volumes/EFI/EFI/CLOVER/acpi/patched/DSDT.aml
		fi
	fi
fi
rm -rf /tmp/tempDSDT

exit $exitcode