#!/bin/bash
if [ ! -r "$HOME/Desktop/Tools" ];
then
	mkdir "$HOME/Desktop/Tools"
	chown "$USER" "$HOME/Desktop/Tools"
fi
unzip "/tmp/apps/ShowAllFiles.zip" -d "/tmp/apps/"
cp -Rf "/tmp/apps/ShowAllFiles.app" "$HOME/Desktop/Tools/"
chown -R "$USER" "$HOME/Desktop/Tools/ShowAllFiles.app"
