#!/bin/bash
# rebilding the kext cache, if triggered
RebuildOn=`/usr/libexec/PlistBuddy -c "Print :KextCacheRebuild" /tmp/PBI.plist`
if [ "$RebuildOn" == "yes" ]
then
	osxver=`/usr/libexec/PlistBuddy -c 'Print ProductVersion' "${3}"/System/Library/CoreServices/SystemVersion.plist`
	case $osxver in
	10.9*)	echo "OS X Mavericks $osxver detected."
			cp -rf /Volumes/EFI/EFI/CLOVER/kexts/10.9/*  /System/Library/Extensions/;;
	10.10*)	echo "OS X Yosemite $osxver detected."
			cp -rf /Volumes/EFI/EFI/CLOVER/kexts/10.10/*  /System/Library/Extensions/;;
	*)		echo "Unknown or unsupported OS X version, aborting.";;
	esac
	
	diskutil repairPermissions / 
	touch "${3}/System/Library/Extensions"
fi
# setting the Installer Backups folder's owner to the current user
if [ -e "$HOME/Desktop/Installer Backups" ]
then
	chown -R $USER "$HOME/Desktop/Installer Backups"
fi
# deleting temporary files
rm -rf /tmp/PBI.plist
rm -rf /tmp/Apps
# enabling AirDrop
pmset -a hibernatemode 0
defaults write com.apple.NetworkBrowser BrowseAllInterfaces 1