#!/bin/bash
set -x
PBIplist="/tmp/PBI.plist"
if [ -e "$PBIplist" ]
then
	rm -rf "$PBIplist"
fi
/usr/libexec/PlistBuddy -c "Add :CurrentDateTime string `date '+%Y-%m-%d %H-%M'`" "$PBIplist"
/usr/libexec/PlistBuddy -c "Add :KextCacheRebuild string 'no'" "$PBIplist"
/usr/libexec/PlistBuddy -c "Add :CloverModel string 'no'" "$PBIplist"
/usr/libexec/PlistBuddy -c "Add :CloverResolution string 'no'" "$PBIplist"
/usr/libexec/PlistBuddy -c "Add :CloverHD4600 string 'no'" "$PBIplist"
/usr/libexec/PlistBuddy -c "Add :CloverConfigGenerate string 'yes'" "$PBIplist"

if [ -d "/Volumes/EFI" ]
then
    if mount | grep /Volumes/EFI > /dev/null; then
		diskutil unmount /Volumes/EFI
	else
		rm -rf /Volumes/EFI
	fi
fi

if [ -d "/Volumes/ESP" ]
then
	if mount | grep /Volumes/ESP > /dev/null; then
		diskutil unmount /Volumes/ESP
	else
		rm -rf /Volumes/ESP
	fi
fi

if [ -d "/tmp/tempDSDT" ]
then
	rm -rf /tmp/tempDSDT
fi