#!/bin/bash
PBIplist="/tmp/PBI.plist"
if [ -e "$PBIplist" ]
then
	rm -rf "$PBIplist"
fi
/usr/libexec/PlistBuddy -c "Add :CurrentDateTime string `date '+%Y-%m-%d %H-%M'`" "$PBIplist"
/usr/libexec/PlistBuddy -c "Add :KextCacheRebuild string 'no'" "$PBIplist"
/usr/libexec/PlistBuddy -c "Add :CloverModel string 'no'" "$PBIplist"
/usr/libexec/PlistBuddy -c "Add :CloverResolution string 'no'" "$PBIplist"

if [ -d "/Volumes/EFI" ]
then
	diskutil unmount /Volumes/EFI
fi

if [ -d "/Volumes/ESP" ]
then
	diskutil unmount /Volumes/ESP
fi