#!/bin/bash
set -x
RightNowIs=`/usr/libexec/PlistBuddy -c "Print :CurrentDateTime" /tmp/PBI.plist`
BackupDir="$HOME/Desktop/Installer Backups/Backup $RightNowIs"

Kexts=("BTFirmwareUploader.kext" "BrcmPatchRAM.kext" "IOath3kfrmwr.kext" "BrcmBluetoothInjector.kext")
for kext in ${Kexts[@]}; 
do
if [ -e "/System/Library/Extensions/$kext" ]
then
	if [ ! -e "$BackupDir" ]
	then
		mkdir -p "$BackupDir"
	fi
	cp -Rf "/System/Library/Extensions/$kext" "$BackupDir"
	rm -rf "/System/Library/Extensions/$kext"
fi
done