#!/bin/bash

RightNowIs=`/usr/libexec/PlistBuddy -c "Print :CurrentDateTime" /tmp/PBI.plist`
BackupDir="$HOME/Desktop/Installer Backups/Backup $RightNowIs"


if [ ! -d /Volumes/EFI/EFI/CLOVER/kexts/10.10 ]
then
	mkdir -p /Volumes/EFI/EFI/CLOVER/kexts/10.10
fi

rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.10/*
cp -rf /Volumes/EFI/EFI/CLOVER/kexts/10.9/* /Volumes/EFI/EFI/CLOVER/kexts/10.10
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.9/FakePCIID_HD4600_HD4400.kext
#rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.9/FakePCIID.kext

osxver=`/usr/libexec/PlistBuddy -c 'Print ProductVersion' "${3}"/System/Library/CoreServices/SystemVersion.plist`
case $osxver in
10.9*)	echo "OS X Mavericks $osxver detected."
		cp -rf /Volumes/EFI/EFI/CLOVER/kexts/10.9/*  /System/Library/Extensions/
10.10*)	echo "OS X Yosemite $osxver detected."
		cp -rf /Volumes/EFI/EFI/CLOVER/kexts/10.10/*  /System/Library/Extensions/
*)		echo "Unknown or unsupported OS X version, aborting.";;

systemsetup -setwakeonnetworkaccess off
/usr/libexec/PlistBuddy -c "Set :KextCacheRebuild yes" /tmp/PBI.plist