#!/bin/bash

RightNowIs=`/usr/libexec/PlistBuddy -c "Print :CurrentDateTime" /tmp/PBI.plist`
BackupDir="$HOME/Desktop/Installer Backups/Backup $RightNowIs"

./BackupESP
./Backup.sh ./list_common ${3}

rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.9/*