#!/bin/sh

# generate Clover config file
CloverModel=`/usr/libexec/PlistBuddy -c "Print :CloverModel" /tmp/PBI.plist`
CloverResolution=`/usr/libexec/PlistBuddy -c "Print :CloverResolution" /tmp/PBI.plist`
CloverHD4600=`/usr/libexec/PlistBuddy -c "Print :CloverHD4600" /tmp/PBI.plist`
osxver=`/usr/libexec/PlistBuddy -c 'Print ProductVersion' "${3}"/System/Library/CoreServices/SystemVersion.plist`

if [ "$CloverModel" != "no" ]
then

	config="/tmp/config.plist"	

	# header 
	printf '<?xml version="1.0" encoding="UTF-8"?>\n' > $config
	printf '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n' >> $config
	printf '<plist version="1.0">\n' >> $config
	printf '<dict>\n' >> $config

	# graphics section
	printf '\t<key>Graphics</key>\n' >> $config
	printf '\t<dict>\n' >> $config

	if [ "$CloverModel" == "4x0G1" ] || [ "$CloverModel" == "4x0G2" ]
	then
		printf '\t\t<key>ig-platform-id</key>\n' >> $config
		printf '\t\t<string>0x0a260006</string>\n' >> $config
		printf '\t\t<key>Inject</key>\n' >> $config
		printf '\t\t<dict>\n' >> $config
		printf '\t\t\t<key>Intel</key>\n' >> $config
		printf '\t\t\t<true/>\n' >> $config
		printf '\t\t\t<key>ATI</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t\t<key>NVidia</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t</dict>\n' >> $config
	elif [ "$CloverModel" == "6x70AMD" ]
	then
		printf '\t\t<key>DualLink</key>\n' >> $config
		printf '\t\t<integer>1</integer>\n' >> $config
		printf '\t\t<key>FBName</key>\n' >> $config
		printf '\t\t<string>Typha</string>\n' >> $config
		printf '\t\t<key>Inject</key>\n' >> $config
		printf '\t\t<dict>\n' >> $config
		printf '\t\t\t<key>Intel</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t\t<key>ATI</key>\n' >> $config
		printf '\t\t\t<true/>\n' >> $config
		printf '\t\t\t<key>NVidia</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t</dict>\n' >> $config
		printf '\t\t<key>LoadVBios</key>\n' >> $config
		printf '\t\t<true/>\n' >> $config
	elif [ "$CloverModel" == "6x60wAMD" ]
	then
		printf '\t\t<key>Inject</key>\n' >> $config
		printf '\t\t<dict>\n' >> $config
		printf '\t\t\t<key>Intel</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t\t<key>ATI</key>\n' >> $config
		printf '\t\t\t<true/>\n' >> $config
		printf '\t\t\t<key>NVidia</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t</dict>\n' >> $config
		printf '\t\t<key>LoadVBios</key>\n' >> $config
		printf '\t\t<true/>\n' >> $config
	else
		case $CloverResolution in 
			low)
				printf '\t\t<key>DualLink</key>\n' >> $config
				printf '\t\t<integer>0</integer>\n' >> $config
				printf '\t\t<key>ig-platform-id</key>\n' >> $config
				printf '\t\t<string>0x01660003</string>\n' >> $config
				printf '\t\t<key>Inject</key>\n' >> $config
				printf '\t\t<dict>\n' >> $config
				printf '\t\t\t<key>Intel</key>\n' >> $config
				printf '\t\t\t<false/>\n' >> $config
				printf '\t\t\t<key>ATI</key>\n' >> $config
				printf '\t\t\t<false/>\n' >> $config
				printf '\t\t\t<key>NVidia</key>\n' >> $config
				printf '\t\t\t<false/>\n' >> $config
				printf '\t\t</dict>\n' >> $config
				;;
			high)
				printf '\t\t<key>DualLink</key>\n' >> $config
				printf '\t\t<integer>1</integer>\n' >> $config
				printf '\t\t<key>ig-platform-id</key>\n' >> $config
				printf '\t\t<string>0x01660004</string>\n' >> $config
				printf '\t\t<key>Inject</key>\n' >> $config
				printf '\t\t<dict>\n' >> $config
				printf '\t\t\t<key>Intel</key>\n' >> $config
				printf '\t\t\t<false/>\n' >> $config
				printf '\t\t\t<key>ATI</key>\n' >> $config
				printf '\t\t\t<false/>\n' >> $config
				printf '\t\t\t<key>NVidia</key>\n' >> $config
				printf '\t\t\t<false/>\n' >> $config
				printf '\t\t</dict>\n' >> $config
				;;
		esac
	fi

	printf '\t</dict>\n' >> $config

	# smbios section
	week=CDFGHJKLMNPQRTVWXY12345678
	week2=012345678
	chars=ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
	week_letter=`echo ${week:$(($RANDOM%${#week})):1}`
	week_letter2=`echo ${week:$(($RANDOM%${#week2})):2}`

	boardserial=""
	mlb=""
	rom=""

	function random_char { echo ${chars:$(($RANDOM%${#chars})):1}; }

	if [ -f /Volumes/EFI/EFI/CLOVER/config.plist ]
	then
		mlb=$(/usr/libexec/PlistBuddy -c 'Print :RtVariables:MLB' /Volumes/EFI/EFI/CLOVER/config.plist)
		rom=$(/usr/libexec/PlistBuddy -c 'Print :RtVariables:ROM' /Volumes/EFI/EFI/CLOVER/config.plist)
		boardserial=$(/usr/libexec/PlistBuddy -c 'Print :SMBIOS:BoardSerialNumber' /Volumes/EFI/EFI/CLOVER/config.plist)
		if [[ "$boardserial" == "*Does Not Exist" ]]
		then
			if [[ "$mlb" == "*Does Not Exist" ]]
			then
				boardserial="$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)"
			else
				boardserial="$mlb"
			fi
		fi
	else
		boardserial="$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)$(random_char)"
	fi
	
	
	case $CloverModel in 
		4x30|6x60*)
			boardtype="10"
			chassistype="8"
			chassis="MacBook-Aluminum"
			family="MacBook Pro"
			mobile="true"

			biosdate="04/22/11"
			biosversion="MBP81.88Z.0047.B0E.1104221557"
			boardprod="Mac-94245B3640C91C81"
			prodname="MacBookPro8,1"
			serial="C02J"$week_letter$(random_char)$(random_char)$(random_char)"DH2G"
			;;
		4x40*|6x70*|4x0G0)
			boardtype="10"
			chassistype="8"
			chassis="MacBook-Aluminum"
			family="MacBook Pro"
			mobile="true"

			biosdate="08/08/12"
			biosversion="MBP91.88Z.00D3.B08.1208081132"
			boardprod="Mac-6F01561E16C75D06"
			prodname="MacBookPro9,2"
			serial="C02L"$week_letter$(random_char)$(random_char)$(random_char)"DTY3"
			;;		
		9470)
			boardtype="10"
			chassistype="10"
			chassis="Air-Enclosure"
			family="MacBook Air"
			mobile="true"

			biosdate="05/10/12"
			biosversion="MBA51.88Z.00EF.B00.1205221442"
			boardprod="Mac-2E6FAB96566FE58C"
			prodname="MacBookAir5,2"
			serial="C02L"$week_letter$(random_char)$(random_char)$(random_char)"DRVC"
			;;
		4x0G1|4x0G2)
			boardtype="10"
			chassistype="8"
			chassis="MacBook-Aluminum"
			family="MacBook Pro"
			mobile="true"

			biosdate="10/18/13"
			biosversion="MBP112.88Z.0138.B02.1310181745"
			boardprod="Mac-3CBD00234E554E41"
			prodname="MacBookPro11,2"
			serial="C02L"$week_letter$(random_char)$(random_char)$(random_char)"FD58"
			;;
	esac

	# check existing serial number
	if [ -f /Volumes/EFI/EFI/CLOVER/config.plist ]
	then
		oldprodname=$(/usr/libexec/PlistBuddy -c 'Print :SMBIOS:ProductName' /Volumes/EFI/EFI/CLOVER/config.plist)
		if [ "$oldprodname" == "$prodname" ]
		then
			oldserial=$(/usr/libexec/PlistBuddy -c 'Print :SMBIOS:SerialNumber' /Volumes/EFI/EFI/CLOVER/config.plist)
			if ! [[ "$oldserial" == "*Does Not Exist" ]]
			then
				serial=$oldserial
			fi
		fi
	fi

	printf '\t<key>SMBIOS</key>\n' >> $config
	printf '\t<dict>\n' >> $config
	printf '\t\t<key>BoardType</key>\n' >> $config
	printf '\t\t<integer>'"$boardtype"'</integer>\n' >> $config
	printf '\t\t<key>ChassisType</key>\n' >> $config
	printf '\t\t<integer>'"$chassistype"'</integer>\n' >> $config
	printf '\t\t<key>BiosReleaseDate</key>\n' >> $config
	printf '\t\t<string>'"$biosdate"'</string>\n' >> $config
	printf '\t\t<key>Version</key>\n' >> $config
	printf '\t\t<string>1.0</string>\n' >> $config
	printf '\t\t<key>SerialNumber</key>\n' >> $config
	printf '\t\t<string>'"$serial"'</string>\n' >> $config
	printf '\t\t<key>Manufacturer</key>\n' >> $config
	printf '\t\t<string>Apple Inc.</string>\n' >> $config
	printf '\t\t<key>BoardManufacturer</key>\n' >> $config
	printf '\t\t<string>Apple Inc.</string>\n' >> $config
	printf '\t\t<key>ChassisAssetTag</key>\n' >> $config
	printf '\t\t<string>'"$chassis"'</string>\n' >> $config
	printf '\t\t<key>BiosVendor</key>\n' >> $config
	printf '\t\t<string>Apple Inc.</string>\n' >> $config
	printf '\t\t<key>ChassisManufacturer</key>\n' >> $config
	printf '\t\t<string>Apple Inc.</string>\n' >> $config
	printf '\t\t<key>BiosVersion</key>\n' >> $config
	printf '\t\t<string>'"$biosversion"'</string>\n' >> $config
	printf '\t\t<key>Board-ID</key>\n' >> $config
	printf '\t\t<string>'"$boardprod"'</string>\n' >> $config
	printf '\t\t<key>Family</key>\n' >> $config
	printf '\t\t<string>'"$family"'</string>\n' >> $config
	printf '\t\t<key>ProductName</key>\n' >> $config
	printf '\t\t<string>'"$prodname"'</string>\n' >> $config

	if ! [[ "$boardserial" == '' ]]
		then
			printf '\t\t<key>BoardSerialNumber</key>\n' >> $config
			printf '\t\t<string>'"$boardserial"'</string>\n' >> $config
		fi
	
	printf '\t\t<key>Mobile</key>\n' >> $config
	printf '\t\t<'"$mobile"'/>\n' >> $config
	printf '\t\t<key>Trust</key>\n' >> $config
	printf '\t\t<false/>\n' >> $config
	printf '\t</dict>\n' >> $config
	
	# RTVariables section

	if ! [[ "$rom" == "*Does Not Exist" ]]
	then
		printf '\t<key>RtVariables</key>\n' >> $config
		printf '\t<dict>\n' >> $config
		printf '\t\t<key>ROM</key>\n' >> $config
		printf '\t\t<string>'"$rom"'</string>\n' >> $config
		printf '\t</dict>\n' >> $config
	fi

	# boot section

	printf '\t<key>Boot</key>\n' >> $config
	printf '\t<dict>\n' >> $config

	if [ "$CloverModel" == "9470" ] || [ "$CloverModel" == "6x70AMD" ] 
	then
		printf '\t\t<key>Arguments</key>\n' >> $config
		printf '\t\t<string>-xcpm kext-dev-mode=1 dart=0</string>\n' >> $config
	elif [ "$CloverModel" == "4x0G1" ] || [ "$CloverModel" == "4x0G2" ]
	then
		printf '\t\t<key>Arguments</key>\n' >> $config
		printf '\t\t<string>-gux_defer_usb2 kext-dev-mode=1 dart=0</string>\n' >> $config
	else
		printf '\t\t<key>Arguments</key>\n' >> $config
		printf '\t\t<string>kext-dev-mode=1 dart=0</string>\n' >> $config
	fi

	printf '\t\t<key>Legacy</key>\n' >> $config
	printf '\t\t<string>LegacyBiosDefault</string>\n' >> $config
	printf '\t\t<key>Log</key>\n' >> $config
	printf '\t\t<false/>\n' >> $config
	printf '\t\t<key>NeverHibernate</key>\n' >> $config
	printf '\t\t<false/>\n' >> $config
	printf '\t\t<key>Timeout</key>\n' >> $config
	printf '\t\t<integer>5</integer>\n' >> $config
	printf '\t\t<key>XMPDetection</key>\n' >> $config
	printf '\t\t<string>Yes</string>\n' >> $config
	printf '\t\t<key>Secure</key>\n' >> $config
	printf '\t\t<false/>\n' >> $config
	printf '\t</dict>\n' >> $config

	# acpi section
	printf '\t<key>ACPI</key>\n' >> $config
	printf '\t<dict>\n' >> $config
	printf '\t\t<key>DSDT</key>\n' >> $config
	printf '\t\t<dict>\n' >> $config
	printf '\t\t\t<key>Debug</key>\n' >> $config
	printf '\t\t\t<false/>\n' >> $config
	printf '\t\t\t<key>ReuseFFFF</key>\n' >> $config
	printf '\t\t\t<false/>\n' >> $config
	printf '\t\t\t<key>DropOEM_DSM</key>\n' >> $config
	printf '\t\t\t<false/>\n' >> $config
	printf '\t\t</dict>\n' >> $config
	printf '\t\t<key>DropTables</key>\n' >> $config
	printf '\t\t<array>\n' >> $config
	printf '\t\t\t<dict>\n' >> $config
	printf '\t\t\t\t<key>Signature</key>\n' >> $config
	printf '\t\t\t\t<string>DMAR</string>\n' >> $config
	printf '\t\t\t</dict>\n' >> $config
	printf '\t\t</array>\n' >> $config
	printf '\t\t<key>SSDT</key>\n' >> $config
	printf '\t\t<dict>\n' >> $config
	printf '\t\t\t<key>DropOem</key>\n' >> $config
	printf '\t\t\t<true/>\n' >> $config
	printf '\t\t\t<key>Generate</key>\n' >> $config
	printf '\t\t\t<dict>\n' >> $config
	printf '\t\t\t\t<key>PStates</key>\n' >> $config
	printf '\t\t\t\t<false/>\n' >> $config
	printf '\t\t\t\t<key>CStates</key>\n' >> $config
	printf '\t\t\t\t<false/>\n' >> $config
	printf '\t\t\t</dict>\n' >> $config
	printf '\t\t</dict>\n' >> $config
	printf '\t</dict>\n' >> $config

	# kernel and kext patches section
	printf '\t<key>KernelAndKextPatches</key>\n' >> $config
	printf '\t<dict>\n' >> $config
	
	printf '\t\t<key>AppleRTC</key>\n' >> $config
	printf '\t\t<true/>\n' >> $config

	
	if [ "$CloverModel" == "9470" ] || [ "$CloverModel" == "4x0G1" ] || [ "$CloverModel" == "4x0G2" ] || [ "$CloverModel" == "6x70AMD" ]
	then
		printf '\t\t<key>KernelPm</key>\n' >> $config
		printf '\t\t<true/>\n' >> $config
	else
		printf '\t\t<key>AsusAICPUPM</key>\n' >> $config
		printf '\t\t<true/>\n' >> $config
	fi

	printf '\t\t<key>KextsToPatch</key>\n' >> $config
	printf '\t\t<array>\n' >> $config

	printf '\t\t\t<dict>\n' >> $config
	printf '\t\t\t\t<key>Name</key>\n' >> $config
	printf '\t\t\t\t<string>IOAHCIBlockStorage</string>\n' >> $config
	printf '\t\t\t\t<key>Find</key>\n' >> $config
	printf '\t\t\t\t<data>\n' >> $config
	printf '\t\t\t\tQVBQTEUgU1NE\n' >> $config
	printf '\t\t\t\t</data>\n' >> $config
	printf '\t\t\t\t<key>Replace</key>\n' >> $config
	printf '\t\t\t\t<data>\n' >> $config
	printf '\t\t\t\tAAAAAAAAAAAA\n' >> $config
	printf '\t\t\t\t</data>\n' >> $config
	printf '\t\t\t\t<key>Comment</key>\n' >> $config
	printf '\t\t\t\t<string>Enable Trim on SSD</string>\n' >> $config
	printf '\t\t\t</dict>\n' >> $config
	
	printf '\t\t\t<dict>\n' >> $config
	printf '\t\t\t\t<key>Name</key>\n' >> $config
	printf '\t\t\t\t<string>IOGraphicsFamily</string>\n' >> $config
	printf '\t\t\t\t<key>Find</key>\n' >> $config
	printf '\t\t\t\t<data>\n' >> $config
	printf '\t\t\t\thcB0XUg=\n' >> $config
	printf '\t\t\t\t</data>\n' >> $config
	printf '\t\t\t\t<key>Replace</key>\n' >> $config
	printf '\t\t\t\t<data>\n' >> $config
	printf '\t\t\t\tMcB0W0g=\n' >> $config
	printf '\t\t\t\t</data>\n' >> $config
	printf '\t\t\t\t<key>Comment</key>\n' >> $config
	printf '\t\t\t\t<string>Second Stage patch 1 10.10</string>\n' >> $config
	printf '\t\t\t</dict>\n' >> $config

	printf '\t\t\t<dict>\n' >> $config
	printf '\t\t\t\t<key>Name</key>\n' >> $config
	printf '\t\t\t\t<string>IOGraphicsFamily</string>\n' >> $config
	printf '\t\t\t\t<key>Find</key>\n' >> $config
	printf '\t\t\t\t<data>\n' >> $config
	printf '\t\t\t\tQYjE6wM=\n' >> $config
	printf '\t\t\t\t</data>\n' >> $config
	printf '\t\t\t\t<key>Replace</key>\n' >> $config
	printf '\t\t\t\t<data>\n' >> $config
	printf '\t\t\t\tQYjE6yM=\n' >> $config
	printf '\t\t\t\t</data>\n' >> $config
	printf '\t\t\t\t<key>Comment</key>\n' >> $config
	printf '\t\t\t\t<string>Second Stage patch 2 10.10</string>\n' >> $config
	printf '\t\t\t</dict>\n' >> $config

	findsmbios=$(printf "Mac-2E6FAB96566FE58C" | base64)
	patchsmbios=$(printf "$boardprod" | base64)

	printf '\t\t\t<dict>\n' >> $config
	printf '\t\t\t\t<key>Name</key>\n' >> $config
	printf '\t\t\t\t<string>AirPortBrcm4360</string>\n' >> $config
	printf '\t\t\t\t<key>Find</key>\n' >> $config
	printf '\t\t\t\t<data>\n' >> $config
	printf '\t\t\t\t'"$findsmbios"'\n' >> $config
	printf '\t\t\t\t</data>\n' >> $config
	printf '\t\t\t\t<key>Replace</key>\n' >> $config
	printf '\t\t\t\t<data>\n' >> $config
	printf '\t\t\t\t'"$patchsmbios"'\n' >> $config
	printf '\t\t\t\t</data>\n' >> $config
	printf '\t\t\t\t<key>Comment</key>\n' >> $config
	printf '\t\t\t\t<string>Broadcom 43224 whitelist</string>\n' >> $config
	printf '\t\t\t</dict>\n' >> $config

	printf '\t\t\t<dict>\n' >> $config
	printf '\t\t\t\t<key>Name</key>\n' >> $config
	printf '\t\t\t\t<string>AirPortBrcm4360</string>\n' >> $config
	printf '\t\t\t\t<key>Find</key>\n' >> $config
	printf '\t\t\t\t<data>\n' >> $config
	printf '\t\t\t\tWFQAKxgsIQAg\n' >> $config
	printf '\t\t\t\t</data>\n' >> $config
	printf '\t\t\t\t<key>Replace</key>\n' >> $config
	printf '\t\t\t\t<data>\n' >> $config
	printf '\t\t\t\tWFQICjYcRwAK\n' >> $config
	printf '\t\t\t\t</data>\n' >> $config
	printf '\t\t\t\t<key>Comment</key>\n' >> $config
	printf '\t\t\t\t<string>Broadcom 5Ghz XT</string>\n' >> $config
	printf '\t\t\t</dict>\n' >> $config

	printf '\t\t\t<dict>\n' >> $config
	printf '\t\t\t\t<key>Name</key>\n' >> $config
	printf '\t\t\t\t<string>AirPortBrcm4360</string>\n' >> $config
	printf '\t\t\t\t<key>Find</key>\n' >> $config
	printf '\t\t\t\t<data>\n' >> $config
	printf '\t\t\t\taxAAAHUN\n' >> $config
	printf '\t\t\t\t</data>\n' >> $config
	printf '\t\t\t\t<key>Replace</key>\n' >> $config
	printf '\t\t\t\t<data>\n' >> $config
	printf '\t\t\t\taxAAAJCQ\n' >> $config
	printf '\t\t\t\t</data>\n' >> $config
	printf '\t\t\t\t<key>Comment</key>\n' >> $config
	printf '\t\t\t\t<string>Broadcom Airport Extreme</string>\n' >> $config
	printf '\t\t\t</dict>\n' >> $config

	printf '\t\t\t<dict>\n' >> $config
	printf '\t\t\t\t<key>Name</key>\n' >> $config
	printf '\t\t\t\t<string>IOBluetoothFamily</string>\n' >> $config
	printf '\t\t\t\t<key>Find</key>\n' >> $config
	printf '\t\t\t\t<data>\n' >> $config
	printf '\t\t\t\ti4eMAQAA\n' >> $config
	printf '\t\t\t\t</data>\n' >> $config
	printf '\t\t\t\t<key>Replace</key>\n' >> $config
	printf '\t\t\t\t<data>\n' >> $config
	printf '\t\t\t\tuA8AAACQ\n' >> $config
	printf '\t\t\t\t</data>\n' >> $config
	printf '\t\t\t\t<key>Comment</key>\n' >> $config
	printf '\t\t\t\t<string>Handoff Fix</string>\n' >> $config
	printf '\t\t\t</dict>\n' >> $config


	
	if [ "$CloverModel" == "4x30" ] || [ "$CloverModel" == "6x60" ] || [ "$CloverModel" == "4x40sb" ]
	then
		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleIntelSNBGraphicsFB</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tAQIEABAHAAAQBwAABQMAAAIAAAAwAAAAAgUAAAAEAAAHAAAAAwQAAAAEAAAJAAAABAYAAAAEAAAJAAAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tAQIDABAHAAAQBwAABgIAAAABAAAJAAAABQMAAAIAAAAwAAAABAYAAAAIAAAJAAAAAAAAAAAAAAAAAAAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch VGA port HD3000</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config
	elif ([ "$CloverModel" == "4x40" ] || [ "$CloverModel" == "6x70" ] || [ "$CloverModel" == "4x0G0" ] || [ "$CloverModel" == "9470" ]) && [ "$CloverResolution" == "low" ]
	then
		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleIntelFramebufferCapri</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tBAYAAAAEAACBAAAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tBAYAAAAIAAAGAAAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch audio HDMI HD4000 1366x768</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config
	elif ([ "$CloverModel" == "4x40" ] || [ "$CloverModel" == "6x70" ] || [ "$CloverModel" == "4x0G0" ] || [ "$CloverModel" == "9470" ]) && [ "$CloverResolution" == "high" ]
	then
		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleIntelFramebufferCapri</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tBABmAQEDAQEAAAAC\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tBABmAQECBAIAAAAE\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch HDMI-DP port HD4000 1600x900 #1</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config

		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleIntelFramebufferCapri</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tMAIAAAAAAAABAAAAQAAAAAAAAAABAAAAQAAAAAAAAAABAAAAQAAAAAAAAAAAAAAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tMAIAAAIFAAAABAAABwQAAAMEAAAABAAAgQAAAAQGAAAACAAABgAAAAAAAAAAAgAR\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch HDMI-DP port HD4000 1600x900 #2</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config
	elif ([ "$CloverModel" == "4x0G1" ] || [ "$CloverModel" == "4x0G2" ])
	then
		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleIntelFramebufferAzul</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tBgAmCgEDAwMAAAACAAAwAQAAYAAAAABg2QoAANkKAAAA\n' >> $config
		printf '\t\t\t\tAAAAAAAAAAAACAACAAAAMAAAAAEFCQAABAAAhwAAAAIE\n' >> $config
		printf '\t\t\t\tCQAABAAAhwAAAP8AAAABAAAAQAAAAA8AAAABAQAABAAA\n' >> $config
		printf '\t\t\t\tAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAA=\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tBgAmCgEDAwMAAAACAAAAAQAAYAAAAABA2QoAANkKAAAA\n' >> $config
		printf '\t\t\t\tAAAAAAAAAAAAEAACAAAAMAAAAAEFEgAACAAAhwAAAAIE\n' >> $config
		printf '\t\t\t\tEgAACAAAhwAAAP8AAQABAAAAQAAAAA8AAAABAQAABAAA\n' >> $config
		printf '\t\t\t\tAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAA=\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch audio HDMI HD4400/4600 laptop</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config
	elif ([ "$CloverModel" == "6x70AMD" ])
	then
		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AMD6000Controller</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tAAQAAAQDAAAAAQEAEQIEAQAEAAAEAwAAAAECACEDBQIA
                BAAAAAEAAAAJAwAQAAIFAAQAAAABAAAACQQAIAEDBgQA
                AAAUAgAAAAEFAAIEAQM=\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tAgAAAEAAAAAJAQAAEAEAAQAEAAAEAwAAAAECABECAQUA
                BAAABAIAAAABAgAhAgICAAQAAAQCAAAAAQAAEgADAxAA
                AAAQAAAAAAEAAAAABAg=\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch AMD port</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config
	fi

	if [ "$CloverHD4600" == "yes" ] && [ "$osxver" == "10.10" ]
	then
		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleIntelFramebufferAzul</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tPYaAEgQ=\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tPYaAFgQ=\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch HD4600 10.10</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config

		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleIntelHD5000Graphics</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tPYaAEgR0EOtd\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tPYaAFgR0EOtd\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch HD4600 10.10</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config
	fi
	
	case $CloverModel in 
		4x30)
			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\thBnUEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\t0XYdEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>IDT 76D1</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config
			;;
		4x40*)
			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\thBnUEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\t2XYdEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>IDT 76D9</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config
			;;		
		4x0G0|9470|4x0G1)
			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\thBnUEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tAAAAAA==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>IDT 76E0</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config

			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tixnUEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\t4HYdEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>IDT 76E0</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config
			;;
		4x0G2)
			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\thAjsEA==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tAAAAAA==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>ALC 282</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config

			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\thQjsEA==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tAAAAAA==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>ALC 282</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config

			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\thBnUEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tggLsEA==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>ALC 282</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config
			;;
		6x60*|6x70*)
			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\thBnUEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tAAAAAA==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>IDT 7605</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config

			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tixnUEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tBXYdEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>IDT 7605</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config
			;;
	esac
	

	printf '\t\t</array>\n' >> $config

	printf '\t</dict>\n' >> $config

	# gui section
	printf '\t<key>GUI</key>\n' >> $config
	printf '\t<dict>\n' >> $config
	CurrentTheme=''
	if [ -f /Volumes/EFI/EFI/CLOVER/config.plist ]
	then
		CurrentTheme=$(/usr/libexec/PlistBuddy -c 'Print :GUI:Theme' /Volumes/EFI/EFI/CLOVER/config.plist)
		if [[ "$CurrentTheme" == "*Does Not Exist" ]]
		then
			CurrentTheme=''
		fi
	fi

	if ( ( [ "$CloverModel" == "4x0G1" ] || [ "$CloverModel" == "4x0G2" ] || [ "$CloverModel" == "4x40" ] || [ "$CloverModel" == "6x70" ] || [ "$CloverModel" == "4x0G0" ] || [ "$CloverModel" == "9470" ] || [ "$CloverModel" == "6x70AMD" ] ) && [ "$CloverResolution" == "high" ] )
	then
		if [[ "$CurrentTheme" == '' ]]
		then
			CurrentTheme='Yosemite'
		fi

		printf '\t\t<key>Theme</key>\n' >> $config
		printf '\t\t<string>'"$CurrentTheme"'</string>\n' >> $config
	else
		if [[ "$CurrentTheme" == '' ]]
		then
			CurrentTheme='Yosemite S'
		fi
		printf '\t\t<key>ScreenResolution</key>\n' >> $config
		printf '\t\t<string>1024x768</string>\n' >> $config
		printf '\t\t<key>Theme</key>\n' >> $config
		printf '\t\t<string>'"$CurrentTheme"'</string>\n' >> $config
	fi
	
	printf '\t\t<key>Mouse</key>\n' >> $config
	printf '\t\t<dict>\n' >> $config
	printf '\t\t\t<key>Enabled</key>\n' >> $config
	printf '\t\t\t<false/>\n' >> $config
	printf '\t\t</dict>\n' >> $config
	printf '\t\t<key>Scan</key>\n' >> $config
	printf '\t\t<dict>\n' >> $config
	printf '\t\t\t<key>Entries</key>\n' >> $config
	printf '\t\t\t<true/>\n' >> $config
	printf '\t\t\t<key>Tool</key>\n' >> $config
	printf '\t\t\t<true/>\n' >> $config
	printf '\t\t\t<key>Legacy</key>\n' >> $config
	printf '\t\t\t<false/>\n' >> $config
	printf '\t\t</dict>\n' >> $config
	printf '\t\t<key>Custom</key>\n' >> $config
	printf '\t\t<dict>\n' >> $config
	printf '\t\t\t<key>Entries</key>\n' >> $config
	printf '\t\t\t<array>\n' >> $config
	printf '\t\t\t\t<dict>\n' >> $config
	printf '\t\t\t\t<key>FullTitle</key>\n' >> $config
	printf '\t\t\t\t<string>UEFI Internal</string>\n' >> $config
	printf '\t\t\t\t<key>Hidden</key>\n' >> $config
	printf '\t\t\t\t<string>Always</string>\n' >> $config
	printf '\t\t\t\t<key>Disabled</key>\n' >> $config
	printf '\t\t\t\t<false/>\n' >> $config
	printf '\t\t\t\t<key>Type</key>\n' >> $config
	printf '\t\t\t\t<string>Other</string>\n' >> $config
	printf '\t\t\t\t</dict>\n' >> $config
	printf '\t\t\t</array>\n' >> $config
	printf '\t\t</dict>\n' >> $config
	printf '\t</dict>\n' >> $config

	# devices section
	printf '\t<key>Devices</key>\n' >> $config
	printf '\t<dict>\n' >> $config

	if [ "$CloverHD4600" == "yes" ] && [ "$osxver" == "10.10" ]
	then
		printf '\t\t<key>FakeID</key>\n' >> $config
		printf '\t\t<dict>\n' >> $config
		printf '\t\t\t<key>IntelGFX</key>\n' >> $config
		printf '\t\t\t<string>0x04128086</string>\n' >> $config
		printf '\t\t</dict>\n' >> $config
	fi

	printf '\t\t<key>USB</key>\n' >> $config
	printf '\t\t<dict>\n' >> $config
	printf '\t\t\t<key>Inject</key>\n' >> $config
	printf '\t\t\t<false/>\n' >> $config
	printf '\t\t\t<key>FixOwnership</key>\n' >> $config
	printf '\t\t\t<false/>\n' >> $config
	printf '\t\t\t<key>AddClockID</key>\n' >> $config
	printf '\t\t\t<false/>\n' >> $config
	printf '\t\t</dict>\n' >> $config
	printf '\t</dict>\n' >> $config

	# system parameters section
	printf '\t<key>SystemParameters</key>\n' >> $config
	printf '\t<dict>\n' >> $config
	printf '\t\t<key>InjectKexts</key>\n' >> $config
	printf '\t\t<string>Detect</string>\n' >> $config
	printf '\t</dict>\n' >> $config

	# end
	printf '\t</dict>\n' >> $config
	printf '\t</plist>\n' >> $config

	chown "$USER" "$config"
fi