#!/bin/sh

# generate Clover config file
CloverModel=`/usr/libexec/PlistBuddy -c "Print :CloverModel" /tmp/PBI.plist`
CloverResolution=`/usr/libexec/PlistBuddy -c "Print :CloverResolution" /tmp/PBI.plist`
#CloverHD4600=`/usr/libexec/PlistBuddy -c "Print :CloverHD4600" /tmp/PBI.plist`
osxver=`/usr/libexec/PlistBuddy -c 'Print ProductVersion' "${3}"/System/Library/CoreServices/SystemVersion.plist`

if [ "$CloverModel" != "no" ]
then
	
	if [ "$CloverResolution" == "no" ]
	then
	/usr/bin/osascript <<EOT
tell application "Finder"
    activate
    display dialog "If you see this warning message, that means:

	You didn't select display resolution in PBI CE.

If you want to make yourself a new patched DSDT, you should do the following:

Press F4 at Clover screen
Run PBI Clover Edition again and select correct DSDT options." buttons {"OK"} default button "OK" with icon note with title "Missing display resolution!"
end tell
EOT
	fi


	config="/tmp/config.plist"	

	# header 
	printf '<?xml version="1.0" encoding="UTF-8"?>\n' > $config
	printf '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n' >> $config
	printf '<plist version="1.0">\n' >> $config
	printf '<dict>\n' >> $config

	# graphics section
	printf '\t<key>Graphics</key>\n' >> $config
	printf '\t<dict>\n' >> $config

	if [ "$CloverModel" == "4x0G1" ] || [ "$CloverModel" == "4x0G2" ] || [ "$CloverModel" == "3x0G1" ] || [ "$CloverModel" == "ZBook" ]
	then
		printf '\t\t<key>ig-platform-id</key>\n' >> $config
		printf '\t\t<string>0x0a260006</string>\n' >> $config
		printf '\t\t<key>Inject</key>\n' >> $config
		printf '\t\t<dict>\n' >> $config
		printf '\t\t\t<key>Intel</key>\n' >> $config
		printf '\t\t\t<true/>\n' >> $config
		printf '\t\t\t<key>ATI</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t\t<key>NVidia</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t</dict>\n' >> $config
	elif [ "$CloverModel" == "4x0G2Broadwell" ]
	then
		printf '\t\t<key>ig-platform-id</key>\n' >> $config
		printf '\t\t<string>0x16260006</string>\n' >> $config
		printf '\t\t<key>Inject</key>\n' >> $config
		printf '\t\t<dict>\n' >> $config
		printf '\t\t\t<key>Intel</key>\n' >> $config
		printf '\t\t\t<true/>\n' >> $config
		printf '\t\t\t<key>ATI</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t\t<key>NVidia</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t</dict>\n' >> $config
	elif [ "$CloverModel" == "6x70AMD" ]
	then
		case $CloverResolution in 
			low)
				printf '\t\t<key>DualLink</key>\n' >> $config
				printf '\t\t<integer>0</integer>\n' >> $config
				;;
			high)
				printf '\t\t<key>DualLink</key>\n' >> $config
				printf '\t\t<integer>1</integer>\n' >> $config
				;;
		esac
		printf '\t\t<key>FBName</key>\n' >> $config
		printf '\t\t<string>Ebi</string>\n' >> $config
		printf '\t\t<key>Inject</key>\n' >> $config
		printf '\t\t<dict>\n' >> $config
		printf '\t\t\t<key>Intel</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t\t<key>ATI</key>\n' >> $config
		printf '\t\t\t<true/>\n' >> $config
		printf '\t\t\t<key>NVidia</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t</dict>\n' >> $config
		printf '\t\t<key>LoadVBios</key>\n' >> $config
		printf '\t\t<true/>\n' >> $config
	elif [ "$CloverModel" == "6x70NVIDIA" ]
	then
		case $CloverResolution in 
			low)
				printf '\t\t<key>DualLink</key>\n' >> $config
				printf '\t\t<integer>0</integer>\n' >> $config
				;;
			high)
				printf '\t\t<key>DualLink</key>\n' >> $config
				printf '\t\t<integer>1</integer>\n' >> $config
				;;
		esac
		
		printf '\t\t<key>Inject</key>\n' >> $config
		printf '\t\t<dict>\n' >> $config
		printf '\t\t\t<key>Intel</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t\t<key>ATI</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t\t<key>NVidia</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t</dict>\n' >> $config
		printf '\t\t<key>LoadVBios</key>\n' >> $config
		printf '\t\t<true/>\n' >> $config
	elif [ "$CloverModel" == "6x60wAMD" ]
	then
		case $CloverResolution in 
			low)
				printf '\t\t<key>DualLink</key>\n' >> $config
				printf '\t\t<integer>0</integer>\n' >> $config
				;;
			high)
				printf '\t\t<key>DualLink</key>\n' >> $config
				printf '\t\t<integer>1</integer>\n' >> $config
				;;
		esac
		printf '\t\t<key>FBName</key>\n' >> $config
		printf '\t\t<string>Cattail</string>\n' >> $config
		printf '\t\t<key>Inject</key>\n' >> $config
		printf '\t\t<dict>\n' >> $config
		printf '\t\t\t<key>Intel</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t\t<key>ATI</key>\n' >> $config
		printf '\t\t\t<true/>\n' >> $config
		printf '\t\t\t<key>NVidia</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t</dict>\n' >> $config
		printf '\t\t<key>LoadVBios</key>\n' >> $config
		printf '\t\t<true/>\n' >> $config
	elif [ "$CloverModel" == "6x60wNVIDIA" ]
	then
		case $CloverResolution in 
			low)
				printf '\t\t<key>DualLink</key>\n' >> $config
				printf '\t\t<integer>0</integer>\n' >> $config
				;;
			high)
				printf '\t\t<key>DualLink</key>\n' >> $config
				printf '\t\t<integer>1</integer>\n' >> $config
				;;
		esac
		printf '\t\t<key>Inject</key>\n' >> $config
		printf '\t\t<dict>\n' >> $config
		printf '\t\t\t<key>Intel</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t\t<key>ATI</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t\t<key>NVidia</key>\n' >> $config
		printf '\t\t\t<true/>\n' >> $config
		printf '\t\t</dict>\n' >> $config
		printf '\t\t<key>LoadVBios</key>\n' >> $config
		printf '\t\t<true/>\n' >> $config
	elif [ "$CloverModel" == "6x60pAMD" ]
	then
		case $CloverResolution in 
			low)
				printf '\t\t<key>DualLink</key>\n' >> $config
				printf '\t\t<integer>0</integer>\n' >> $config
				;;
			high)
				printf '\t\t<key>DualLink</key>\n' >> $config
				printf '\t\t<integer>1</integer>\n' >> $config
				;;
		esac
		printf '\t\t<key>FBName</key>\n' >> $config
		printf '\t\t<string>Elodea</string>\n' >> $config
		printf '\t\t<key>Inject</key>\n' >> $config
		printf '\t\t<dict>\n' >> $config
		printf '\t\t\t<key>Intel</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t\t<key>ATI</key>\n' >> $config
		printf '\t\t\t<true/>\n' >> $config
		printf '\t\t\t<key>NVidia</key>\n' >> $config
		printf '\t\t\t<false/>\n' >> $config
		printf '\t\t</dict>\n' >> $config
		printf '\t\t<key>LoadVBios</key>\n' >> $config
		printf '\t\t<true/>\n' >> $config
		printf '\t\t<key>InjectEDID</key>\n' >> $config
		printf '\t\t<true/>\n' >> $config
		printf '\t\t<key>VRAM</key>\n' >> $config
		printf '\t\t<integer>1024</integer>\n' >> $config
		printf '\t\t<key>VideoPorts</key>\n' >> $config
		printf '\t\t<integer>5</integer>\n' >> $config
	else
		case $CloverResolution in 
			low)
				printf '\t\t<key>DualLink</key>\n' >> $config
				printf '\t\t<integer>0</integer>\n' >> $config
				printf '\t\t<key>ig-platform-id</key>\n' >> $config
				printf '\t\t<string>0x01660003</string>\n' >> $config
				printf '\t\t<key>Inject</key>\n' >> $config
				printf '\t\t<dict>\n' >> $config
				printf '\t\t\t<key>Intel</key>\n' >> $config
				printf '\t\t\t<false/>\n' >> $config
				printf '\t\t\t<key>ATI</key>\n' >> $config
				printf '\t\t\t<false/>\n' >> $config
				printf '\t\t\t<key>NVidia</key>\n' >> $config
				printf '\t\t\t<false/>\n' >> $config
				printf '\t\t</dict>\n' >> $config
				;;
			high)
				printf '\t\t<key>DualLink</key>\n' >> $config
				printf '\t\t<integer>1</integer>\n' >> $config
				printf '\t\t<key>ig-platform-id</key>\n' >> $config
				printf '\t\t<string>0x01660004</string>\n' >> $config
				printf '\t\t<key>Inject</key>\n' >> $config
				printf '\t\t<dict>\n' >> $config
				printf '\t\t\t<key>Intel</key>\n' >> $config
				printf '\t\t\t<false/>\n' >> $config
				printf '\t\t\t<key>ATI</key>\n' >> $config
				printf '\t\t\t<false/>\n' >> $config
				printf '\t\t\t<key>NVidia</key>\n' >> $config
				printf '\t\t\t<false/>\n' >> $config
				printf '\t\t</dict>\n' >> $config
				;;
		esac
	fi

	printf '\t</dict>\n' >> $config

	# smbios section
	week=CDFGHJKLMNPQRTVWXY12345678
	week2=012345678
	chars=ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
	week_letter=`echo ${week:$(($RANDOM%${#week})):1}`
	week_letter2=`echo ${week:$(($RANDOM%${#week2})):2}`

	boardserial=""
	mlb=""
	rom=""
	ModelY=""

	function random_char { echo ${chars:$(($RANDOM%${#chars})):1}; }

	if [ -f /Volumes/EFI/EFI/CLOVER/config.plist ]
	then
		mlb=$(/usr/libexec/PlistBuddy -c 'Print :RtVariables:MLB' /Volumes/EFI/EFI/CLOVER/config.plist 2>null)
		rom=$(/usr/libexec/PlistBuddy -c 'Print :RtVariables:ROM' /Volumes/EFI/EFI/CLOVER/config.plist 2>null)
		boardserial=$(/usr/libexec/PlistBuddy -c 'Print :SMBIOS:BoardSerialNumber' /Volumes/EFI/EFI/CLOVER/config.plist 2>null)
		if [[ "$boardserial" == "" ]] || [[ "$boardserial" == Error* ]]
		then
			if [[ "$mlb" == "" ]] || [[ "$mlb" == Error* ]]
			then
				boardserial=""
			else 
				boardserial="$mlb"
			fi
		fi
	else
		boardserial=""
	fi
	
	
	case $CloverModel in 
		6x60pAMD|6x60wAMD)
			boardtype="10"
			chassistype="8"
			chassis="MacBook-Aluminum"
			family="MacBook Pro"
			mobile="true"

			biosdate="10/14/11"
			biosversion="MBP81.88Z.0047.B24.1110141131"
			boardprod="Mac-94245A3940C91C80"
			prodname="MacBookPro8,2"
			serial="C02J"$week_letter$(random_char)$(random_char)$(random_char)"DF8X"
			ModelY="1"
			;;
		6x60wNVIDIA)
			boardtype="10"
			chassistype="8"
			chassis="MacBook-Aluminum"
			family="MacBook Pro"
			mobile="true"

			biosdate="12/21/12"
			biosversion="MBP101.88Z.00EE.B03.1212211437"
			boardprod="Mac-C3EC7CD22292981F"
			prodname="MacBookPro10,1"
			serial="C02J"$week_letter$(random_char)$(random_char)$(random_char)"DKQ1"
			ModelY="2"
			;;
		4x30|6x60)
			boardtype="10"
			chassistype="8"
			chassis="MacBook-Aluminum"
			family="MacBook Pro"
			mobile="true"

			biosdate="01/24/12"
			biosversion="MBP81.88Z.0047.B27.1201241646"
			boardprod="Mac-94245B3640C91C81"
			prodname="MacBookPro8,1"
			serial="C02J"$week_letter$(random_char)$(random_char)$(random_char)"DH2G"
			ModelY="1"
			;;
		4x40*|6x70*|4x0G0)
			boardtype="10"
			chassistype="8"
			chassis="MacBook-Aluminum"
			family="MacBook Pro"
			mobile="true"

			biosdate="08/08/12"
			biosversion="MBP91.88Z.00D3.B08.1208081132"
			boardprod="Mac-6F01561E16C75D06"
			prodname="MacBookPro9,2"
			serial="C02L"$week_letter$(random_char)$(random_char)$(random_char)"DTY3"
			ModelY="2"
			;;		
		9470)
			boardtype="10"
			chassistype="10"
			chassis="Air-Enclosure"
			family="MacBook Air"
			mobile="true"

			biosdate="05/10/12"
			biosversion="MBA51.88Z.00EF.B00.1205221442"
			boardprod="Mac-2E6FAB96566FE58C"
			prodname="MacBookAir5,2"
			serial="CK2"$week_letter2$(random_char)$(random_char)$(random_char)"DRVC"
			ModelY="2"
			;;
		4x0G1|4x0G2|3x0G1|ZBook)
			boardtype="10"
			chassistype="8"
			chassis="MacBook-Aluminum"
			family="MacBook Pro"
			mobile="true"

			biosdate="10/29/13"
			biosversion="MBP111.88Z.0138.B03.1310291227"
			boardprod="Mac-189A3D4F975D5FFC"
			prodname="MacBookPro11,1"
			serial="C02L"$week_letter$(random_char)$(random_char)$(random_char)"FGYY"
			ModelY="3"
			;;
		4x0G2Broadwell)
			boardtype="10"
			chassistype="10"
			chassis="Air-Enclosure"
			family="MacBook Air"
			mobile="true"

			biosdate="03/24/15"
			biosversion="MBA71.88Z.0166.B02.1503241251"
			boardprod="Mac-937CB26E2E02BB01"
			prodname="MacBookAir7,2"
			serial="C1M"$week_letter2$(random_char)$(random_char)$(random_char)"G944"

			ModelY="5"
			;;
	esac

	# check existing serial number
	if [ -f /Volumes/EFI/EFI/CLOVER/config.plist ]
	then
		oldprodname=$(/usr/libexec/PlistBuddy -c 'Print :SMBIOS:ProductName' /Volumes/EFI/EFI/CLOVER/config.plist 2>null)
		if [ "$oldprodname" == "$prodname" ]
		then
			oldserial=$(/usr/libexec/PlistBuddy -c 'Print :SMBIOS:SerialNumber' /Volumes/EFI/EFI/CLOVER/config.plist 2>null)
			if [[ "$oldserial" != "" ]] && [[ "$oldserial" != Error* ]]
			then
				serial=$oldserial
			fi
		fi
	fi

	printf '\t<key>SMBIOS</key>\n' >> $config
	printf '\t<dict>\n' >> $config
	printf '\t\t<key>BoardType</key>\n' >> $config
	printf '\t\t<integer>'"$boardtype"'</integer>\n' >> $config
	printf '\t\t<key>ChassisType</key>\n' >> $config
	printf '\t\t<integer>'"$chassistype"'</integer>\n' >> $config
	printf '\t\t<key>BiosReleaseDate</key>\n' >> $config
	printf '\t\t<string>'"$biosdate"'</string>\n' >> $config
	printf '\t\t<key>Version</key>\n' >> $config
	printf '\t\t<string>1.0</string>\n' >> $config
	printf '\t\t<key>SerialNumber</key>\n' >> $config
	printf '\t\t<string>'"$serial"'</string>\n' >> $config
	printf '\t\t<key>Manufacturer</key>\n' >> $config
	printf '\t\t<string>Apple Inc.</string>\n' >> $config
	printf '\t\t<key>BoardManufacturer</key>\n' >> $config
	printf '\t\t<string>Apple Inc.</string>\n' >> $config
	printf '\t\t<key>ChassisAssetTag</key>\n' >> $config
	printf '\t\t<string>'"$chassis"'</string>\n' >> $config
	printf '\t\t<key>BiosVendor</key>\n' >> $config
	printf '\t\t<string>Apple Inc.</string>\n' >> $config
	printf '\t\t<key>ChassisManufacturer</key>\n' >> $config
	printf '\t\t<string>Apple Inc.</string>\n' >> $config
	printf '\t\t<key>BiosVersion</key>\n' >> $config
	printf '\t\t<string>'"$biosversion"'</string>\n' >> $config
	printf '\t\t<key>Board-ID</key>\n' >> $config
	printf '\t\t<string>'"$boardprod"'</string>\n' >> $config
	printf '\t\t<key>Family</key>\n' >> $config
	printf '\t\t<string>'"$family"'</string>\n' >> $config
	printf '\t\t<key>ProductName</key>\n' >> $config
	printf '\t\t<string>'"$prodname"'</string>\n' >> $config

	if [[ "$boardserial" == '' ]]
	then

		WeekN=$(echo $[ ( $RANDOM % 53 ) ])
		while [  $WeekN -eq 0 ]; do
			WeekN=$(echo $[ ( $RANDOM % 53 ) ])
		done
		WeekNU=$(printf "%02d" $WeekN)

		rm temp
		BASE62=($(echo {0..9} {a..z} {A..Z}))
		NUM=$(($RANDOM*7584284))
		ProductionN=$(echo $NUM | cut -c 1-5)
		for i in $(bc <<< "obase=36; $ProductionN"); do
			echo ${BASE62[$(( 10#$i ))]} | tr "\\n" "," | tr -d , >> temp
		done
		SSS=$(cat temp | tr '[:lower:]' '[:upper:]')

		rm tempy
		NUMB=$(($RANDOM*7584284))
		PartN=$(echo $NUMB | cut -c 1-8)
		for m in $(bc <<< "obase=36; $PartN"); do
			echo ${BASE62[$(( 10#$m ))]} | tr "\\n" "," | tr -d , >> tempy
		done
		CCCC=$(cat tempy | cut -c 1-4 | tr '[:lower:]' '[:upper:]')


		boardserial="C02"$ModelY$WeekNU$SSS$CCCC
	fi

	printf '\t\t<key>BoardSerialNumber</key>\n' >> $config
	printf '\t\t<string>'"$boardserial"'</string>\n' >> $config

	
	printf '\t\t<key>Mobile</key>\n' >> $config
	printf '\t\t<'"$mobile"'/>\n' >> $config
	printf '\t\t<key>Trust</key>\n' >> $config
	printf '\t\t<true/>\n' >> $config
	printf '\t</dict>\n' >> $config
	
	# RTVariables section
	printf '\t<key>RtVariables</key>\n' >> $config
	printf '\t<dict>\n' >> $config

	if ! [[ "$rom" == "*Does Not Exist" ]] && [[ "$rom" != '' ]]
	then
		printf '\t\t<key>ROM</key>\n' >> $config
		printf '\t\t<string>'"$rom"'</string>\n' >> $config
	fi

	printf '\t\t<key>CsrActiveConfig</key>\n' >> $config
	printf '\t\t<string>0x67</string>\n' >> $config
	printf '\t\t<key>BooterConfig</key>\n' >> $config
	printf '\t\t<string>0x28</string>\n' >> $config
	printf '\t</dict>\n' >> $config

	# boot section

	printf '\t<key>Boot</key>\n' >> $config
	printf '\t<dict>\n' >> $config

	if [ "$CloverModel" == "9470" ] || [ "$CloverModel" == "6x70AMD" ] || [ "$CloverModel" == "6x70NVIDIA" ] 
	then
		printf '\t\t<key>Arguments</key>\n' >> $config
		printf '\t\t<string>-xcpm kext-dev-mode=1 dart=0 rootless=0</string>\n' >> $config
	elif [ "$CloverModel" == "4x0G1" ] || [ "$CloverModel" == "3x0G1" ] || [ "$CloverModel" == "ZBook" ] || [ "$CloverModel" == "4x0G2Broadwell" ] 
	then
		printf '\t\t<key>Arguments</key>\n' >> $config
		printf '\t\t<string>kext-dev-mode=1 dart=0 rootless=0</string>\n' >> $config
	elif [ "$CloverModel" == "4x0G2" ]
	then
		printf '\t\t<key>Arguments</key>\n' >> $config
		printf '\t\t<string>kext-dev-mode=1 dart=0 darkwake=0 rootless=0</string>\n' >> $config
	else
		printf '\t\t<key>Arguments</key>\n' >> $config
		printf '\t\t<string>kext-dev-mode=1 dart=0 rootless=0</string>\n' >> $config
	fi

	printf '\t\t<key>Legacy</key>\n' >> $config
	printf '\t\t<string>LegacyBiosDefault</string>\n' >> $config
	printf '\t\t<key>Log</key>\n' >> $config
	printf '\t\t<false/>\n' >> $config
	printf '\t\t<key>NeverHibernate</key>\n' >> $config
	printf '\t\t<true/>\n' >> $config
	printf '\t\t<key>Timeout</key>\n' >> $config
	printf '\t\t<integer>5</integer>\n' >> $config
	printf '\t\t<key>XMPDetection</key>\n' >> $config
	printf '\t\t<string>Yes</string>\n' >> $config
	printf '\t\t<key>Secure</key>\n' >> $config
	printf '\t\t<false/>\n' >> $config
	printf '\t</dict>\n' >> $config

	# acpi section
	printf '\t<key>ACPI</key>\n' >> $config
	printf '\t<dict>\n' >> $config
	printf '\t\t<key>DSDT</key>\n' >> $config
	printf '\t\t<dict>\n' >> $config
	printf '\t\t\t<key>Debug</key>\n' >> $config
	printf '\t\t\t<false/>\n' >> $config
	printf '\t\t\t<key>ReuseFFFF</key>\n' >> $config
	printf '\t\t\t<false/>\n' >> $config
	printf '\t\t\t<key>DropOEM_DSM</key>\n' >> $config
	printf '\t\t\t<false/>\n' >> $config
	printf '\t\t</dict>\n' >> $config
	printf '\t\t<key>DropTables</key>\n' >> $config
	printf '\t\t<array>\n' >> $config
	printf '\t\t\t<dict>\n' >> $config
	printf '\t\t\t\t<key>Signature</key>\n' >> $config
	printf '\t\t\t\t<string>DMAR</string>\n' >> $config
	printf '\t\t\t</dict>\n' >> $config
	if [ "$CloverModel" == "6x60pAMD" ] || [ "$CloverModel" == "6x60wAMD" ] || [ "$CloverModel" == "6x60wNVIDIA" ]
	then
		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Signature</key>\n' >> $config
		printf '\t\t\t\t<string>MCFG</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config
	fi
	printf '\t\t</array>\n' >> $config
	printf '\t\t<key>SSDT</key>\n' >> $config
	printf '\t\t<dict>\n' >> $config
	printf '\t\t\t<key>DropOem</key>\n' >> $config
	printf '\t\t\t<true/>\n' >> $config
	printf '\t\t\t<key>Generate</key>\n' >> $config
	printf '\t\t\t<dict>\n' >> $config
	printf '\t\t\t\t<key>PStates</key>\n' >> $config
	printf '\t\t\t\t<false/>\n' >> $config
	printf '\t\t\t\t<key>CStates</key>\n' >> $config
	printf '\t\t\t\t<false/>\n' >> $config
	printf '\t\t\t</dict>\n' >> $config
	printf '\t\t</dict>\n' >> $config
	printf '\t</dict>\n' >> $config

	# kernel and kext patches section
	printf '\t<key>KernelAndKextPatches</key>\n' >> $config
	printf '\t<dict>\n' >> $config

	if [ "$CloverModel" == "6x60pAMD" ]
	then
		printf '\t\t<key>ATIConnectorsController</key>\n' >> $config
		printf '\t\t<string>6000</string>\n' >> $config
		printf '\t\t<key>ATIConnectorsData</key>\n' >> $config
		printf '\t\t<string>0200000000010000090100001204030300040000040300000001000010000505000400000403000000010000110201010004000000010000000910002103020200040000000100000009100022050404</string>\n' >> $config
		printf '\t\t<key>ATIConnectorsPatch</key>\n' >> $config
		printf '\t\t<string>0200000040000000090100001001010500040000040300000001000011020204000400000403000000010000210303020004000004030000000100001204040310000000100000000001000000000001</string>\n' >> $config
	elif [ "$CloverModel" == "6x60wAMD" ]
	then
		printf '\t\t<key>ATIConnectorsController</key>\n' >> $config
		printf '\t\t<string>6000</string>\n' >> $config
		printf '\t\t<key>ATIConnectorsData</key>\n' >> $config
		printf '\t\t<string>020000004000000029050000000000050004000004030000000100001102010100040000000100000009100021030202</string>\n' >> $config
		printf '\t\t<key>ATIConnectorsPatch</key>\n' >> $config
		printf '\t\t<string>100000001000000000010000000000020200000040000000290500001000010500040000040300000001000012040203</string>\n' >> $config
	elif [ "$CloverModel" == "6x70AMD" ]
	then
		printf '\t\t<key>ATIConnectorsController</key>\n' >> $config
		printf '\t\t<string>6000</string>\n' >> $config
		printf '\t\t<key>ATIConnectorsData</key>\n' >> $config
		printf '\t\t<string>0004000004030000000101001102040100040000040300000001020021030502000400000001000000090300100002050004000000010000000904002001030604000000140200000001050002040103</string>\n' >> $config
		printf '\t\t<key>ATIConnectorsPatch</key>\n' >> $config
		printf '\t\t<string>0200000040000000090100001001000100040000040300000001020011020105000400000402000000010200210202020004000004020000000100001200030310000000100000000001000000000408</string>\n' >> $config
	fi
	
	printf '\t\t<key>AppleRTC</key>\n' >> $config
	printf '\t\t<true/>\n' >> $config

	

	if [ "$CloverModel" == "4x30" ] || [ "$CloverModel" == "4x40" ] || [[ $CloverModel == 6x60* ]] || [ "$CloverModel" == "6x70" ]
	then
		printf '\t\t<key>AsusAICPUPM</key>\n' >> $config
		printf '\t\t<true/>\n' >> $config
	else
		printf '\t\t<key>KernelPm</key>\n' >> $config
		printf '\t\t<true/>\n' >> $config
	fi

	printf '\t\t<key>KextsToPatch</key>\n' >> $config
	printf '\t\t<array>\n' >> $config

	printf '\t\t\t<dict>\n' >> $config
	printf '\t\t\t\t<key>Name</key>\n' >> $config
	printf '\t\t\t\t<string>IOAHCIBlockStorage</string>\n' >> $config
	printf '\t\t\t\t<key>Find</key>\n' >> $config
	printf '\t\t\t\t<data>\n' >> $config
	printf '\t\t\t\tQVBQTEUgU1NE\n' >> $config
	printf '\t\t\t\t</data>\n' >> $config
	printf '\t\t\t\t<key>Replace</key>\n' >> $config
	printf '\t\t\t\t<data>\n' >> $config
	printf '\t\t\t\tAAAAAAAAAAAA\n' >> $config
	printf '\t\t\t\t</data>\n' >> $config
	printf '\t\t\t\t<key>Comment</key>\n' >> $config
	printf '\t\t\t\t<string>Enable Trim on SSD</string>\n' >> $config
	printf '\t\t\t</dict>\n' >> $config
	
	if [ "$CloverModel" != "6x60pAMD" ] && [ "$CloverModel" != "6x0wAMD" ] && [ "$CloverModel" != "6x60wNVIDIA" ] && [ "$CloverModel" != "6x70AMD" ] && [ "$CloverModel" != "6x70NVIDIA" ]
	then

		if [[ "$osxver" == 10.10* ]]
		then
			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>IOGraphicsFamily</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tQYjE6xE=\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tQYjE6zE=\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>Second Stage patch 10.10</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config
		fi

	fi

	findsmbios=$(printf "Mac-2E6FAB96566FE58C" | base64)
	patchsmbios=$(printf "$boardprod" | base64)

	if [ "$CloverModel" != "4x30" ]
	then
		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AirPortBrcm4360</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\t'"$findsmbios"'\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\t'"$patchsmbios"'\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Broadcom 43224 whitelist</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config

		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AirPortBrcm4360</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tQYP8/3QsSA==\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tZscGVVPrKw==\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Broadcom 5Ghz US</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config


		if [[ "$osxver" == 10.10* ]]
		then
			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>IOBluetoothFamily</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tSIXAdFwPt0g=\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tQb4PAAAA61k=\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>Handoff Fix</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config
		elif [[ "$osxver" == 10.11* ]]
		then
			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>IOBluetoothFamily</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tSIX/dEdIiwc=\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tQb4PAAAA60Q=\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>Handoff Fix</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config
		fi


	fi


	
	if [ "$CloverModel" == "4x30" ] || [ "$CloverModel" == "6x60" ] || [ "$CloverModel" == "4x40sb" ]
	then
		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleIntelSNBGraphicsFB</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tAQIEABAHAAAQBwAABQMAAAIAAAAwAAAAAgUAAAAEAAAHAAAAAwQAAAAEAAAJAAAABAYAAAAEAAAJAAAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tAQIDABAHAAAQBwAABgIAAAABAAAJAAAABQMAAAIAAAAwAAAABAYAAAAIAAAJAAAAAAAAAAAAAAAAAAAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch VGA port HD3000 (disable this if you use HDMI)</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config

		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>disabled:AppleIntelSNBGraphicsFB</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tBAYAAAAEAAAJAAAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tBAYAAAAIAAAJAAAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch HDMI Audio HD3000 (disable this if you use VGA patch)</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config

	elif ([ "$CloverModel" == "4x40" ] || [ "$CloverModel" == "4x0G0" ]) && [ "$CloverResolution" == "low" ]
	then
		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleIntelFramebufferCapri</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tBAYAAAAEAACBAAAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tBAYAAAAIAAAGAAAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch audio HDMI HD4000 1366x768</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config
	elif ([ "$CloverModel" == "4x40" ] || [ "$CloverModel" == "4x0G0" ]) && [ "$CloverResolution" == "high" ]
	then
		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleIntelFramebufferCapri</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tBABmAQEDAQEAAAAC\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tBABmAQECBAIAAAAE\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch HDMI port HD4000 1600x900 #1</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config

		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleIntelFramebufferCapri</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tMAIAAAAAAAABAAAAQAAAAAAAAAABAAAAQAAAAAAAAAABAAAAQAAAAAAAAAAAAAAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tMAIAAAIFAAAABAAABwQAAAMEAAAABAAAgQAAAAQGAAAACAAABgAAAAAAAAAAAgAR\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch HDMI port HD4000 1600x900 #2</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config
	elif ([ "$CloverModel" == "6x70" ] || [ "$CloverModel" == "9470" ]) && [ "$CloverResolution" == "high" ]
	then
		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleIntelFramebufferCapri</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tBABmAQEDAQEAAAAC\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tBABmAQECBAIAAAAE\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch DP port HD4000 1600x900 #1</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config

		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleIntelFramebufferCapri</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tMAIAAAAAAAABAAAAQAAAAAAAAAABAAAAQAAAAAAAAAABAAAAQAAAAAAAAAAAAAAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tMAIAAAIFAAAABAAABwQAAAMEAAAABAAAgQAAAAQGAAAABAAAgQAAAAAAAAAAAgAR\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch DP port HD4000 1600x900 #2</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config
	elif ([ "$CloverModel" == "4x0G1" ] || [ "$CloverModel" == "3x0G1" ] || [ "$CloverModel" == "4x0G2" ])
	then
		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleIntelFramebufferAzul</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tBgAmCgEDAwMAAAACAAAwAQAAYAA=\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tBgAmCgEDAwMAAAACAAAwAQAAkAA=\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch HD4400/4600 9mb Cursor bytes</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config	

		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleIntelFramebufferAzul</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tAQUJAAAEAACHAAAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tAQUSAAAIAACHAAAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch HD4400/4600 HDMI Freeze</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config	
	elif ([ "$CloverModel" == "4x0G2Broadwell" ])
	then
		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleIntelBDWGraphicsFramebuffer</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tAQULAAAEAAAHBQAAAgQLAAAEAAAHBQAA/wAAAAEAAABAAAAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tAQULAAAIAACCAAAAAgQLAAAIAACCAAAA/wAAAAEAAABAAAAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch HD5500 HDMI Audio</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config	
	elif [ "$CloverModel" == "ZBook" ]
	then
		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleIntelFramebufferAzul</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tBgAmCgEDAwMAAAACAAAwAQAAYAA=\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tBgAmCgEDAwMAAAACAAAwAQAAkAA=\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch HD4400/4600 9mb Cursor bytes</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config

		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleIntelFramebufferAzul</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tAgQJAAAEAACHAAAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tAwYDAAAEAACHAAAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>Patch HD4400/4600 DP</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config		
	fi

	if ([ "$CloverModel" == "4x30" ] || [[ $CloverModel == 6x60* ]]) && [[ "$osxver" != 10.11* ]]
	then
		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleUSBXHCI</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\t9oDUAAAAgHU6\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\t9oDUAAAAgOs6\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>USB 3.0 Disable Intel USB3 controller check 10.9</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config

		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleUSBXHCI</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\t9oDUAAAAgHU0\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\t9oDUAAAAgOs0\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>USB 3.0 Disable Intel USB3 controller check 10.10</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config

		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleUSBXHCI</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tZj0AAQ==\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tZj0AAA==\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>USB 3.0 Disable XHCI 1.0 check 10.9</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config

		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleUSBXHCI</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tQbzHAgDgPQABAAA=\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tQbzHAgDgPQAAAAA=\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>USB 3.0 Disable XHCI 1.0 check 10.10</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config

		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleUSBXHCI</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tgUkIAABAAA==\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tgUkIAAAAAA==\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>USB 3.0 Patch MSI or pin interrupts #1</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config

		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleUSBXHCI</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tQcdHCAAAQAA=\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tQcdHCAAAAAA=\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>USB 3.0 Patch MSI or pin interrupts #2</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config

		printf '\t\t\t<dict>\n' >> $config
		printf '\t\t\t\t<key>Name</key>\n' >> $config
		printf '\t\t\t\t<string>AppleUSBXHCI</string>\n' >> $config
		printf '\t\t\t\t<key>Find</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\tdU1Ii7voAQAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Replace</key>\n' >> $config
		printf '\t\t\t\t<data>\n' >> $config
		printf '\t\t\t\t601Ii7voAQAA\n' >> $config
		printf '\t\t\t\t</data>\n' >> $config
		printf '\t\t\t\t<key>Comment</key>\n' >> $config
		printf '\t\t\t\t<string>USB 3.0 Enable PCI power management</string>\n' >> $config
		printf '\t\t\t</dict>\n' >> $config
	fi

	# if [ "$CloverHD4600" == "yes" ] && [[ "$osxver" == 10.10* ]]
	# then
	# 	printf '\t\t\t<dict>\n' >> $config
	# 	printf '\t\t\t\t<key>Name</key>\n' >> $config
	# 	printf '\t\t\t\t<string>AppleIntelFramebufferAzul</string>\n' >> $config
	# 	printf '\t\t\t\t<key>Find</key>\n' >> $config
	# 	printf '\t\t\t\t<data>\n' >> $config
	# 	printf '\t\t\t\tPYaAEgQ=\n' >> $config
	# 	printf '\t\t\t\t</data>\n' >> $config
	# 	printf '\t\t\t\t<key>Replace</key>\n' >> $config
	# 	printf '\t\t\t\t<data>\n' >> $config
	# 	printf '\t\t\t\tPYaAFgQ=\n' >> $config
	# 	printf '\t\t\t\t</data>\n' >> $config
	# 	printf '\t\t\t\t<key>Comment</key>\n' >> $config
	# 	printf '\t\t\t\t<string>Patch HD4600 10.10</string>\n' >> $config
	# 	printf '\t\t\t</dict>\n' >> $config

	# 	printf '\t\t\t<dict>\n' >> $config
	# 	printf '\t\t\t\t<key>Name</key>\n' >> $config
	# 	printf '\t\t\t\t<string>AppleIntelHD5000Graphics</string>\n' >> $config
	# 	printf '\t\t\t\t<key>Find</key>\n' >> $config
	# 	printf '\t\t\t\t<data>\n' >> $config
	# 	printf '\t\t\t\tPYaAEgR0EOtd\n' >> $config
	# 	printf '\t\t\t\t</data>\n' >> $config
	# 	printf '\t\t\t\t<key>Replace</key>\n' >> $config
	# 	printf '\t\t\t\t<data>\n' >> $config
	# 	printf '\t\t\t\tPYaAFgR0EOtd\n' >> $config
	# 	printf '\t\t\t\t</data>\n' >> $config
	# 	printf '\t\t\t\t<key>Comment</key>\n' >> $config
	# 	printf '\t\t\t\t<string>Patch HD4600 10.10</string>\n' >> $config
	# 	printf '\t\t\t</dict>\n' >> $config
	# fi
	
	printf '\t\t\t<dict>\n' >> $config
	printf '\t\t\t\t<key>Name</key>\n' >> $config
	printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
	printf '\t\t\t\t<key>Find</key>\n' >> $config
	printf '\t\t\t\t<data>\n' >> $config
	printf '\t\t\t\tgxnUEQ==\n' >> $config
	printf '\t\t\t\t</data>\n' >> $config
	printf '\t\t\t\t<key>Replace</key>\n' >> $config
	printf '\t\t\t\t<data>\n' >> $config
	printf '\t\t\t\tAAAAAA==\n' >> $config
	printf '\t\t\t\t</data>\n' >> $config
	printf '\t\t\t\t<key>Comment</key>\n' >> $config
	printf '\t\t\t\t<string>AppleHDA Patch 10.11</string>\n' >> $config
	printf '\t\t\t</dict>\n' >> $config
	

	case $CloverModel in 
		4x30)
			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\thBnUEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\t0XYdEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>IDT 76D1</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config
			;;
		4x40*)
			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\thBnUEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\t2XYdEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>IDT 76D9</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config
			;;		
		4x0G0|9470|4x0G1|ZBook)
			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\thBnUEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tAAAAAA==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>IDT 76E0</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config

			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tixnUEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\t4HYdEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>IDT 76E0</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config
			;;
		3x0G1)
			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\thBnUEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tlXYdEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>IDT 7695</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config
			;;
		4x0G2*)
			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\thAjsEA==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tAAAAAA==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>ALC 282</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config

			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\thQjsEA==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tAAAAAA==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>ALC 282</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config

			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\thBnUEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tggLsEA==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>ALC 282</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config
			;;
		6x60*|6x70*)
			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\thBnUEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tAAAAAA==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>IDT 7605</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config

			printf '\t\t\t<dict>\n' >> $config
			printf '\t\t\t\t<key>Name</key>\n' >> $config
			printf '\t\t\t\t<string>AppleHDA</string>\n' >> $config
			printf '\t\t\t\t<key>Find</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tixnUEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Replace</key>\n' >> $config
			printf '\t\t\t\t<data>\n' >> $config
			printf '\t\t\t\tBXYdEQ==\n' >> $config
			printf '\t\t\t\t</data>\n' >> $config
			printf '\t\t\t\t<key>Comment</key>\n' >> $config
			printf '\t\t\t\t<string>IDT 7605</string>\n' >> $config
			printf '\t\t\t</dict>\n' >> $config
			;;
	esac
	

	printf '\t\t</array>\n' >> $config

	printf '\t</dict>\n' >> $config

	# gui section
	printf '\t<key>GUI</key>\n' >> $config
	printf '\t<dict>\n' >> $config
	CurrentTheme=''
	if [ -f /Volumes/EFI/EFI/CLOVER/config.plist ]
	then
		CurrentTheme=$(/usr/libexec/PlistBuddy -c 'Print :GUI:Theme' /Volumes/EFI/EFI/CLOVER/config.plist 2>null)
	fi

	if ( ( [ "$CloverModel" != "6x70AMD" ] && [ "$CloverModel" != "6x70NVIDIA" ]  ) && [ "$CloverResolution" == "low" ] )
	then
		if [[ "$CurrentTheme" == '' ]] || [[ "$CurrentTheme" == Error* ]]
		then
			CurrentTheme='Yosemite S'
		fi
		printf '\t\t<key>ScreenResolution</key>\n' >> $config
		printf '\t\t<string>1024x768</string>\n' >> $config
		printf '\t\t<key>Theme</key>\n' >> $config
		printf '\t\t<string>'"$CurrentTheme"'</string>\n' >> $config	
	else
		if [[ "$CurrentTheme" == '' ]] || [[ "$CurrentTheme" == Error* ]]
		then
			CurrentTheme='Yosemite'
		fi

		printf '\t\t<key>Theme</key>\n' >> $config
		printf '\t\t<string>'"$CurrentTheme"'</string>\n' >> $config
	fi
	
	printf '\t\t<key>Mouse</key>\n' >> $config
	printf '\t\t<dict>\n' >> $config
	printf '\t\t\t<key>Enabled</key>\n' >> $config
	printf '\t\t\t<false/>\n' >> $config
	printf '\t\t</dict>\n' >> $config
	printf '\t\t<key>Scan</key>\n' >> $config
	printf '\t\t<dict>\n' >> $config
	printf '\t\t\t<key>Entries</key>\n' >> $config
	printf '\t\t\t<true/>\n' >> $config
	printf '\t\t\t<key>Tool</key>\n' >> $config
	printf '\t\t\t<true/>\n' >> $config
	printf '\t\t\t<key>Legacy</key>\n' >> $config
	printf '\t\t\t<false/>\n' >> $config
	printf '\t\t</dict>\n' >> $config
	printf '\t\t<key>Custom</key>\n' >> $config
	printf '\t\t<dict>\n' >> $config
	printf '\t\t\t<key>Entries</key>\n' >> $config
	printf '\t\t\t<array>\n' >> $config
	printf '\t\t\t\t<dict>\n' >> $config
	printf '\t\t\t\t\t<key>FullTitle</key>\n' >> $config
	printf '\t\t\t\t\t<string>UEFI Internal</string>\n' >> $config
	printf '\t\t\t\t\t<key>Hidden</key>\n' >> $config
	printf '\t\t\t\t\t<string>Always</string>\n' >> $config
	printf '\t\t\t\t\t<key>Disabled</key>\n' >> $config
	printf '\t\t\t\t\t<false/>\n' >> $config
	printf '\t\t\t\t\t<key>Type</key>\n' >> $config
	printf '\t\t\t\t\t<string>Other</string>\n' >> $config
	printf '\t\t\t\t</dict>\n' >> $config
	printf '\t\t\t</array>\n' >> $config
	printf '\t\t</dict>\n' >> $config
	printf '\t</dict>\n' >> $config

	# devices section
	printf '\t<key>Devices</key>\n' >> $config
	printf '\t<dict>\n' >> $config

	if [ "$CloverModel" == "4x0G1" ] || [ "$CloverModel" == "ZBook" ]  || [ "$CloverModel" == "4x0G2" ] || [ "$CloverModel" == "3x0G1" ]
	then
		printf '\t\t<key>FakeID</key>\n' >> $config
		printf '\t\t<dict>\n' >> $config
		printf '\t\t\t<key>IntelGFX</key>\n' >> $config
		printf '\t\t\t<string>0x04128086</string>\n' >> $config
		printf '\t\t</dict>\n' >> $config
	fi

	printf '\t\t<key>USB</key>\n' >> $config
	printf '\t\t<dict>\n' >> $config
	printf '\t\t\t<key>Inject</key>\n' >> $config
	printf '\t\t\t<false/>\n' >> $config
	printf '\t\t\t<key>FixOwnership</key>\n' >> $config
	printf '\t\t\t<false/>\n' >> $config
	printf '\t\t\t<key>AddClockID</key>\n' >> $config
	printf '\t\t\t<false/>\n' >> $config
	printf '\t\t</dict>\n' >> $config
	printf '\t</dict>\n' >> $config

	# system parameters section
	printf '\t<key>SystemParameters</key>\n' >> $config
	printf '\t<dict>\n' >> $config
	printf '\t\t<key>InjectKexts</key>\n' >> $config
	printf '\t\t<string>Detect</string>\n' >> $config
	printf '\t</dict>\n' >> $config

	# end
	printf '\t</dict>\n' >> $config
	printf '\t</plist>\n' >> $config

	chown "$USER" "$config"
fi