#!/bin/bash
# HP ProBook 4x30s Fix EDID by pokenguyen
GenEDID () {
/usr/libexec/PlistBuddy -c "Print :$1" /tmp/display.plist
rm -f /tmp/EDID.bin
#/usr/libexec/PlistBuddy -x -c 'Print "0"' /tmp/display.plist|tr -d '\n\t'|grep -o 'IODisplayEDID</key><data>[^<]*'|sed 's/.*IODisplayEDID<\/key><data>//'|base64 -D|xxd -p|tr -d '\n\t\s'|sed s/./9/41|sed s/./0/42|xxd -r -p >> /tmp/EDID.bin
EDID=$(/usr/libexec/PlistBuddy -x -c 'Print "0"' /tmp/display.plist|tr -d '\n\t'|grep -o 'IODisplayEDID</key><data>[^<]*'|sed 's/.*IODisplayEDID<\/key><data>//'|base64 -D|xxd -p|tr -d '\n\t\s')
version=${EDID:38:2}
basicparams=${EDID:40:2}
checksum=${EDID:254:2}

newchecksum=$(printf '%x' $((0x$checksum + 0x$version +0x$basicparams - 0x04 - 0x90)) | tail -c 2 )
newedid=${EDID:0:38}0490${EDID:42:212}$newchecksum

echo $newedid|xxd -r -p >> /tmp/EDID.bin

if [ $? -eq 0 ]
then
	RegName=`/usr/libexec/PlistBuddy -c "Print :$1:IORegistryEntryName" /tmp/display.plist`
	DisplayFlags=`/usr/libexec/PlistBuddy -c "Print :$1:IODisplayConnectFlags" /tmp/display.plist`
	VenID=`/usr/libexec/PlistBuddy -c "Print :$1:DisplayVendorID" /tmp/display.plist`
	VenIDhex=`printf '%x\n' $VenID`
	ProdID=`/usr/libexec/PlistBuddy -c "Print :$1:DisplayProductID" /tmp/display.plist`
	ProdIDhex=`printf '%x\n' $ProdID`
	GenDir="${3}/System/Library/Displays/Overrides/DisplayVendorID-$VenIDhex"
	GenFile="DisplayProductID-$ProdIDhex"
	
	if [ "$RegName" == "AppleBacklightDisplay" -o "$DisplayFlags" == "`echo AAgAAA== | base64 -D`" ] || [ "$RegName" == "AppleDisplay" -o "$DisplayFlags" == "`echo AAgAAA== | base64 -D`" ]
	then
		if [ ! -e "$GenDir" ]
		then
			mkdir "$GenDir"
		fi

		/usr/libexec/PlistBuddy -c "Remove :DisplayProductID" "$GenDir/$GenFile"
		/usr/libexec/PlistBuddy -c "Remove :DisplayVendorID" "$GenDir/$GenFile"
		/usr/libexec/PlistBuddy -c "Remove :IODisplayEDID" "$GenDir/$GenFile"

		/usr/libexec/PlistBuddy -c "Add :DisplayProductName string 'HP Display'" "$GenDir/$GenFile"
		/usr/libexec/PlistBuddy -c "Add :test array" "$GenDir/$GenFile"
		/usr/libexec/PlistBuddy -c "Merge /tmp/display.plist :test" "$GenDir/$GenFile"
		/usr/libexec/PlistBuddy -c "Copy :test:$1:DisplayProductID :DisplayProductID" "$GenDir/$GenFile"
		/usr/libexec/PlistBuddy -c "Copy :test:$1:DisplayVendorID :DisplayVendorID" "$GenDir/$GenFile"
		
		/usr/libexec/PlistBuddy -c "Remove :test" "$GenDir/$GenFile"
		/usr/libexec/PlistBuddy -c "Remove :IODisplayEDID" "$GenDir/$GenFile"
		/usr/libexec/PlistBuddy -c "Import :IODisplayEDID /tmp/EDID.bin" "$GenDir/$GenFile"

		#/usr/libexec/PlistBuddy -c "Add :IODisplayEDID data $EDID" "$GenDir/$GenFile"
		chown -R root:wheel "$GenDir" && chmod 755 "$GenDir" && chmod 644 "$GenDir/$GenFile"
	else
		echo "External display detected!"
	fi
else
	echo "No display detected!"
fi	
}
if [ -e /tmp/display.plist ]
then
	rm -rf /tmp/display.plist
fi
case `./ioregpbi -n AppleBacklightDisplay -rxw0` in
	"")	./ioregpbi -n AppleDisplay -arxw0 > /tmp/display.plist
		;;
	*) ./ioregpbi -n AppleBacklightDisplay -arxw0 > /tmp/display.plist
		;;
esac
GenEDID 0 && GenEDID 1 && GenEDID 2
rm -rf /tmp/display.plist
rm -f /tmp/EDID.bin